Repository ArkEcosystem/payvo-sdk, pull requests merged in 2021-11, with the labels that each got.

#316 fix(avax): check all possible sender address variables
  packages/sdk-avax/source/client.service.test.ts
  packages/sdk-avax/source/confirmed-transaction.dto.ts
  packages/sdk-avax/test/fixtures/transactions.json
Labels: bugfix

#317 fix(ark): use timestamp stored in musig server when normalizing transaction
  packages/sdk-ark/source/multi-signature.service.ts
  packages/sdk-lsk/source/multi-signature.service.ts
Labels: bugfix

#310 fix(lsk): omit address filters if recipient is specified
  packages/sdk-lsk/source/client.service.ts
Labels: bugfix

#318 fix(ark): parse unix timestamp stored in musig server
  packages/sdk-ark/source/multi-signature.service.ts
Labels: bugfix

#322 refactor: remove redundant statements in `ClientService` after deleting identifiers from query
  packages/sdk-ark/source/client.service.ts
  packages/sdk-lsk/source/client.service.ts
Labels: refactor

#321 chore(lsk): remove legacy api handling
  packages/sdk-lsk/source/__snapshots__/wallet.dto.test.ts.snap
  packages/sdk-lsk/source/client.service.test.ts
  packages/sdk-lsk/source/confirmed-transaction.dto.ts
  packages/sdk-lsk/source/signed-transaction.dto.test.ts
  packages/sdk-lsk/source/signed-transaction.dto.ts
  packages/sdk-lsk/source/transaction-type.service.ts
  packages/sdk-lsk/source/transaction.dto.test.ts
  packages/sdk-lsk/source/wallet.dto.test.ts
  packages/sdk-lsk/source/wallet.dto.ts
  packages/sdk-lsk/test/fixtures/client/transaction-legacy.json
  packages/sdk-lsk/test/fixtures/client/wallet-legacy-0.json
  packages/sdk-lsk/test/fixtures/client/wallet-legacy-1.json
  packages/sdk-lsk/test/fixtures/client/wallet.json
Labels: chore

#320 feat(lsk): implement `AddressService#fromMultiSignature`
  packages/sdk-lsk/source/address.service.test.ts
  packages/sdk-lsk/source/address.service.ts
  packages/sdk/source/services/address.contract.ts
Labels: feature

#323 feat(sdk): add `ConfirmationSecretSignatory`
  packages/sdk-ark/source/transaction.service.ts
  packages/sdk/source/services/signatory.contract.ts
  packages/sdk/source/services/signatory.service.ts
  packages/sdk/source/signatories/confirmation-secret.ts
  packages/sdk/source/signatories/index.ts
  packages/sdk/source/signatories/signatory.test.ts
  packages/sdk/source/signatories/signatory.ts
Labels: feature

#327 fix(lsk): handle final signature as last participants signature in `PendingMultiSignatureTransaction`
  packages/sdk-lsk/source/multi-signature.service.test.ts
  packages/sdk-lsk/source/multi-signature.transaction.test.ts
  packages/sdk-lsk/source/multi-signature.transaction.ts
Labels: bugfix

#329 chore: bundle `ESM` and `UMD` with `rollup`
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  common/config/rush/browser-approved-packages.json
  common/config/rush/command-line.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  packages/sdk-ada/package.json
  packages/sdk-ark/package.json
  packages/sdk-atom/package.json
  packages/sdk-avax/package.json
  packages/sdk-btc/package.json
  packages/sdk-dot/package.json
  packages/sdk-egld/package.json
  packages/sdk-eos/package.json
  packages/sdk-eth/package.json
  packages/sdk-lsk/package.json
  packages/sdk-luna/package.json
  packages/sdk-nano/package.json
  packages/sdk-neo/package.json
  packages/sdk-sol/package.json
  packages/sdk-trx/package.json
  packages/sdk-xlm/package.json
  packages/sdk-xrp/package.json
  packages/sdk-zil/package.json
  packages/sdk/package.json
Labels: chore

#339 chore: update dependencies
  common/config/rush/browser-approved-packages.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  packages/sdk-ada/package.json
  packages/sdk-ark/package.json
  packages/sdk-atom/package.json
  packages/sdk-avax/package.json
  packages/sdk-btc/package.json
  packages/sdk-btc/source/ledger.service.test.ts
  packages/sdk-btc/source/transaction.service.ledger.test.ts
  packages/sdk-dot/package.json
  packages/sdk-egld/package.json
  packages/sdk-eos/package.json
  packages/sdk-eth/package.json
  packages/sdk-eth/source/address.service.test.ts
  packages/sdk-eth/source/address.service.ts
  packages/sdk-eth/source/key-pair.service.ts
  packages/sdk-eth/source/networks/shared.ts
  packages/sdk-eth/source/private-key.service.ts
  packages/sdk-eth/source/public-key.service.test.ts
  packages/sdk-eth/source/public-key.service.ts
  packages/sdk-eth/source/utils.ts
  packages/sdk-eth/test/fixtures/identity.ts
  packages/sdk-lsk/package.json
  packages/sdk-luna/package.json
  packages/sdk-nano/package.json
  packages/sdk-neo/package.json
  packages/sdk-sol/package.json
  packages/sdk-trx/package.json
  packages/sdk-xlm/package.json
  packages/sdk-xrp/package.json
  packages/sdk-zil/package.json
  packages/sdk-zil/source/address.service.ts
  packages/sdk-zil/source/client.service.ts
  packages/sdk-zil/source/transaction.service.ts
  packages/sdk-zil/source/zilliqa.ts
  packages/sdk/package.json
Labels: chore

#341 chore: update `@elrondnetwork/erdjs`
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  packages/sdk-egld/package.json
Labels: chore

#342 chore: update `stellar-sdk`
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  packages/sdk-xlm/package.json
Labels: chore

#346 feat(trx): implement address validation
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  packages/sdk-trx/package.json
  packages/sdk-trx/source/address.service.test.ts
  packages/sdk-trx/source/address.service.ts
Labels: feature

#347 chore: update `@payvo/helpers` dependency
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  packages/sdk-ada/package.json
  packages/sdk-ark/package.json
  packages/sdk-ark/source/multi-signature.service.ts
  packages/sdk-ark/source/multi-signature.signer.ts
  packages/sdk-atom/package.json
  packages/sdk-avax/package.json
  packages/sdk-avax/source/client.service.ts
  packages/sdk-btc/package.json
  packages/sdk-dot/package.json
  packages/sdk-egld/package.json
  packages/sdk-eos/package.json
  packages/sdk-eth/package.json
  packages/sdk-lsk/package.json
  packages/sdk-luna/package.json
  packages/sdk-nano/package.json
  packages/sdk-neo/package.json
  packages/sdk-sol/package.json
  packages/sdk-trx/package.json
  packages/sdk-xlm/package.json
  packages/sdk-xrp/package.json
  packages/sdk-zil/package.json
  packages/sdk/package.json
  packages/sdk/source/services/link.service.ts
Labels: chore

#351 chore: update `http-fetch` dependency
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  packages/sdk-ada/package.json
  packages/sdk-ark/package.json
  packages/sdk-atom/package.json
  packages/sdk-avax/package.json
  packages/sdk-btc/package.json
  packages/sdk-dot/package.json
  packages/sdk-egld/package.json
  packages/sdk-eos/package.json
  packages/sdk-eth/package.json
  packages/sdk-lsk/package.json
  packages/sdk-luna/package.json
  packages/sdk-nano/package.json
  packages/sdk-nano/source/client.service.test.ts
  packages/sdk-nano/source/rpc.ts
  packages/sdk-neo/package.json
  packages/sdk-sol/package.json
  packages/sdk-trx/package.json
  packages/sdk-xlm/package.json
  packages/sdk-xrp/package.json
  packages/sdk-zil/package.json
  packages/sdk/package.json
Labels: chore

#359 ci: run workflows against node.js 16
  .github/workflows/cd.yml
  .github/workflows/cf.yml
  .github/workflows/ci.yml
  packages/cryptography/.github/stale.yml
  packages/cryptography/.github/workflows/cd.yml
  packages/cryptography/.github/workflows/cf.yml
  packages/cryptography/.github/workflows/ci.yml
  packages/helpers/.github/stale.yml
  packages/helpers/.github/workflows/cd.yml
  packages/helpers/.github/workflows/cf.yml
  packages/helpers/.github/workflows/ci.yml
  packages/http-fetch/.github/stale.yml
  packages/http-fetch/.github/workflows/cd.yml
  packages/http-fetch/.github/workflows/cf.yml
  packages/http-fetch/.github/workflows/ci.yml
  packages/intl/.github/stale.yml
  packages/intl/.github/workflows/cd.yml
  packages/intl/.github/workflows/cf.yml
  packages/intl/.github/workflows/ci.yml
  packages/markets/.github/stale.yml
  packages/markets/.github/workflows/cd.yml
  packages/markets/.github/workflows/cf.yml
  packages/markets/.github/workflows/ci.yml
  packages/news/.github/stale.yml
  packages/news/.github/workflows/cd.yml
  packages/news/.github/workflows/cf.yml
  packages/news/.github/workflows/ci.yml
  packages/profiles/.github/labeler.yml
  packages/profiles/.github/release.yml
  packages/profiles/.github/stale.yml
  packages/profiles/.github/workflows/cd.yml
  packages/profiles/.github/workflows/cf.yml
  packages/profiles/.github/workflows/ci.yml
  packages/profiles/.github/workflows/label.yml
  rush.json
Labels: ci

#362 chore: only run full build for publishing
  packages/ada/package.json
  packages/ark/package.json
  packages/atom/package.json
  packages/avax/package.json
  packages/btc/package.json
  packages/cryptography/package.json
  packages/dot/package.json
  packages/egld/package.json
  packages/eos/package.json
  packages/eth/package.json
  packages/helpers/package.json
  packages/http-fetch/package.json
  packages/intl/package.json
  packages/lsk/package.json
  packages/luna/package.json
  packages/markets/package.json
  packages/nano/package.json
  packages/neo/package.json
  packages/news/package.json
  packages/profiles/package.json
  packages/sdk/package.json
  packages/sol/package.json
  packages/trx/package.json
  packages/xlm/package.json
  packages/xrp/package.json
  packages/zil/package.json
Labels: chore

#361 refactor(btc): use `convertBuffer` and `convertString` from `sdk-helpers`
  packages/btc/source/address.domain.test.ts
  packages/btc/source/address.service.ts
  packages/btc/source/key-pair.service.ts
  packages/btc/source/ledger.service.ts
  packages/btc/source/private-key.service.ts
  packages/btc/source/public-key.service.ts
  packages/btc/source/wallet-data-helper.ts
Labels: refactor

#360 fix(profiles): check against wallet address in password validation
  packages/profiles/source/wallet.mutator.test.ts
  packages/profiles/source/wallet.mutator.ts
Labels: bugfix

#364 refactor: introduce `LedgerTransportFactory`
  packages/ark/package.json
  packages/ark/source/fee.service.test.ts
  packages/ark/source/ledger.service.test.ts
  packages/ark/source/ledger.service.ts
  packages/ark/source/multi-signature.service.test.ts
  packages/ark/source/multi-signature.signer.ts
  packages/ark/source/transaction.service.test.ts
  packages/ark/source/transaction.service.ts
  packages/atom/source/ledger.service.test.ts
  packages/atom/source/ledger.service.ts
  packages/btc/package.json
  packages/btc/source/coin.provider.ts
  packages/btc/source/constants.ts
  packages/btc/source/ledger.service.test.ts
  packages/btc/source/ledger.service.ts
  packages/btc/source/transaction.service.ledger.test.ts
  packages/btc/source/transaction.service.test.ts
  packages/btc/source/transaction.service.ts
  packages/dot/source/ledger.service.test.ts
  packages/dot/source/ledger.service.ts
  packages/eos/source/ledger.service.test.ts
  packages/eos/source/ledger.service.ts
  packages/eth/source/ledger.service.test.ts
  packages/eth/source/ledger.service.ts
  packages/lsk/package.json
  packages/lsk/source/fee.service.test.ts
  packages/lsk/source/ledger.service.test.ts
  packages/lsk/source/ledger.service.ts
  packages/lsk/source/multi-signature.service.test.ts
  packages/lsk/source/transaction.service.test.ts
  packages/neo/source/ledger.service.test.ts
  packages/neo/source/ledger.service.ts
  packages/profiles/source/env.models.ts
  packages/sdk/source/coins/coin-factory.ts
  packages/sdk/source/coins/contracts.ts
  packages/sdk/source/contracts.ts
  packages/sdk/source/ioc/service-provider.contract.ts
  packages/sdk/source/services/ledger.contract.ts
  packages/sdk/source/services/ledger.service.ts
  packages/trx/source/ledger.service.test.ts
  packages/trx/source/ledger.service.ts
  packages/xlm/source/ledger.service.test.ts
  packages/xlm/source/ledger.service.ts
  packages/xrp/source/ledger.service.test.ts
  packages/xrp/source/ledger.service.ts
Labels: refactor

#366 fix(profiles): pass `LedgerTransportFactory` to `CoinFactory`
  packages/profiles/source/coin.service.ts
  packages/profiles/source/container.models.ts
  packages/profiles/source/driver.ts
  packages/profiles/source/env.test.ts
  packages/profiles/test/mocking.ts
  packages/sdk/source/coins/config.ts
Labels: bugfix

#363 chore: update `bip32` dependency
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  packages/btc/package.json
  packages/btc/source/address.domain.ts
  packages/btc/source/address.factory.ts
  packages/btc/source/musig-wallet-data-helper.ts
  packages/btc/source/transaction.service.ts
  packages/btc/source/wallet-data-helper.ts
  packages/cryptography/package.json
  packages/cryptography/source/bip32.ts
  packages/sdk/package.json
Labels: chore

#375 fix(btc): testnet explorer link
  packages/btc/source/link.service.test.ts
  packages/btc/source/networks/btc.testnet.ts
  packages/profiles/source/__snapshots__/env.test.ts.snap
Labels: bugfix

#379 refactor(profiles): update currency formatter to optionally hide ticker
  packages/btc/source/networks/btc.testnet.ts
  packages/profiles/source/helpers/currency.test.ts
  packages/profiles/source/helpers/currency.ts
Labels: refactor

#387 chore(http-fetch): replace `jest` with `uvu`
  packages/http-fetch/source/request.test.js
  packages/test/source/index.ts
Labels: chore

#392 chore(luna): replace `jest` with `uvu`
  .github/workflows/ci.yml
  packages/luna/package.json
  packages/luna/source/link.service.test.js
  packages/luna/source/networks/luna.mainnet.ts
  packages/luna/source/networks/luna.testnet.ts
Labels: chore

#393 chore(sol): replace `jest` with `uvu`
  packages/ada/source/key-pair.service.test.js
  packages/ada/source/private-key.service.test.js
  packages/ada/source/public-key.service.test.js
  packages/atom/source/key-pair.service.test.js
  packages/avax/source/key-pair.service.test.js
  packages/btc/source/key-pair.service.test.js
  packages/dot/source/key-pair.service.test.js
  packages/dot/source/private-key.service.test.js
  packages/dot/source/public-key.service.test.js
  packages/egld/source/key-pair.service.test.js
  packages/egld/source/private-key.service.test.js
  packages/egld/source/public-key.service.test.js
  packages/eth/source/key-pair.service.test.js
  packages/lsk/source/key-pair.service.test.js
  packages/neo/source/key-pair.service.test.js
  packages/sol/source/address.service.test.js
  packages/sol/source/key-pair.service.test.js
  packages/sol/source/link.service.test.js
  packages/sol/source/private-key.service.test.js
  packages/sol/source/public-key.service.test.js
  packages/sol/source/signed-transaction.dto.test.js
  packages/trx/source/key-pair.service.test.js
  packages/xlm/source/keys.service.test.js
  packages/xrp/source/key-pair.service.test.js
Labels: chore

#395 chore(nano): replace `jest` with `uvu`
  packages/ada/source/signed-transaction.dto.test.js
  packages/atom/source/signed-transaction.dto.test.js
  packages/dot/source/signed-transaction.dto.test.js
  packages/egld/source/signed-transaction.dto.test.js
  packages/eos/source/signed-transaction.dto.test.js
  packages/nano/source/client.service.test.js
  packages/nano/source/link.service.test.js
  packages/nano/source/message.service.test.js
  packages/nano/source/signed-transaction.dto.test.js
  packages/nano/source/transaction.service.test.js
  packages/neo/source/signed-transaction.dto.test.js
  packages/xlm/source/signed-transaction.dto.test.js
  packages/xrp/source/signed-transaction.dto.test.js
Labels: chore

#396 chore(neo): replace `jest` with `uvu`
  packages/neo/source/address.service.test.js
  packages/neo/source/client.service.test.js
  packages/neo/source/key-pair.service.test.js
  packages/neo/source/ledger.service.test.js
  packages/neo/source/link.service.test.js
  packages/neo/source/message.service.test.js
  packages/neo/source/message.service.ts
  packages/neo/source/private-key.service.test.js
  packages/neo/source/public-key.service.test.js
  packages/neo/source/signed-transaction.dto.test.js
  packages/neo/source/transaction.dto.test.js
  packages/neo/source/wallet.dto.test.js
  packages/neo/source/wif.service.test.js
Labels: chore

#400 chore(egld): replace `jest` with `uvu`
  packages/egld/source/address.service.test.js
  packages/egld/source/client.service.test.js
  packages/egld/source/key-pair.service.test.js
  packages/egld/source/link.service.test.js
  packages/egld/source/message.service.test.js
  packages/egld/source/private-key.service.test.js
  packages/egld/source/public-key.service.test.js
  packages/egld/source/signed-transaction.dto.test.js
Labels: chore

#401 chore(atom): replace `jest` with `uvu`
  packages/ada/source/transaction.dto.test.js
  packages/ada/source/wallet.dto.test.js
  packages/atom/source/address.service.test.js
  packages/atom/source/client.service.test.js
  packages/atom/source/key-pair.service.test.js
  packages/atom/source/ledger.service.test.js
  packages/atom/source/ledger.service.ts
  packages/atom/source/link.service.test.js
  packages/atom/source/message.service.test.js
  packages/atom/source/private-key.service.test.js
  packages/atom/source/public-key.service.test.js
  packages/atom/source/signed-transaction.dto.test.js
  packages/atom/source/transaction.dto.test.js
  packages/atom/source/transaction.service.test.js
  packages/atom/source/wallet.dto.test.js
  packages/avax/source/signed-transaction.dto.test.js
  packages/btc/source/transaction.dto.test.js
  packages/btc/source/wallet.dto.test.js
  packages/eth/source/wallet.dto.test.js
  packages/lsk/source/client.service.test.js
  packages/lsk/source/signed-transaction.dto.test.js
  packages/lsk/source/transaction.dto.test.js
  packages/profiles/source/wallet.test.js
Labels: chore

#404 refactor(profiles): use total balance in portfolio calculations
  packages/profiles/source/portfolio.test.ts
  packages/profiles/source/portfolio.ts
Labels: refactor

#406 chore(dot): replace `jest` with `uvu`
  packages/ada/source/address.service.test.js
  packages/avax/source/client.service.test.js
  packages/btc/source/address.service.test.js
  packages/dot/source/address.service.test.js
  packages/dot/source/key-pair.service.test.js
  packages/dot/source/ledger.service.test.js
  packages/dot/source/link.service.test.js
  packages/dot/source/message.service.test.js
  packages/dot/source/private-key.service.test.js
  packages/dot/source/public-key.service.test.js
  packages/dot/source/signed-transaction.dto.test.js
  packages/dot/source/transaction.service.test.js
Labels: chore

#407 chore(eth): replace `jest` with `uvu`
  packages/dot/source/address.service.test.js
  packages/dot/source/key-pair.service.test.js
  packages/dot/source/message.service.test.js
  packages/dot/source/private-key.service.test.js
  packages/dot/source/public-key.service.test.js
  packages/dot/source/signed-transaction.dto.test.js
  packages/dot/source/transaction.service.test.js
  packages/eth/source/address.service.test.js
  packages/eth/source/client.service.test.js
  packages/eth/source/fee.service.test.js
  packages/eth/source/key-pair.service.test.js
  packages/eth/source/ledger.service.test.js
  packages/eth/source/ledger.service.ts
  packages/eth/source/link.service.test.js
  packages/eth/source/private-key.service.test.js
  packages/eth/source/transaction.dto.test.js
  packages/eth/source/wallet.dto.test.js
Labels: chore

#408 chore(lsk): replace `jest` with `uvu`
  packages/lsk/source/address.service.test.js
  packages/lsk/source/asset.serializer.test.js
  packages/lsk/source/client.service.test.js
  packages/lsk/source/fee.service.test.js
  packages/lsk/source/key-pair.service.test.js
  packages/lsk/source/ledger.service.test.js
  packages/lsk/source/link.service.test.js
  packages/lsk/source/message.service.test.js
  packages/lsk/source/multi-signature.service.test.js
  packages/lsk/source/multi-signature.transaction.test.js
  packages/lsk/source/private-key.service.test.js
  packages/lsk/source/public-key.service.test.js
  packages/lsk/source/signed-transaction.dto.test.js
  packages/lsk/source/signed-transaction.dto.ts
  packages/lsk/source/timestamps.ts
  packages/lsk/source/transaction.dto.test.js
  packages/lsk/source/transaction.serializer.test.js
  packages/lsk/source/transaction.service.test.js
  packages/lsk/source/wallet.dto.test.js
  packages/lsk/source/wif.service.test.js
  packages/test/source/assert.ts
Labels: chore

#413 ci: run tests in a single workflow
  .github/workflows/ci.yml
  packages/sdk/source/http-response.test.js
  packages/sdk/source/network.test.js
  packages/sdk/source/signatory.test.js
Labels: ci

#417 chore: configure testing with coverage via `c8`
  .eslintignore
  .github/workflows/ci.yml
  .prettierignore
  common/config/rush/browser-approved-packages.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  packages/ada/package.json
  packages/ark/package.json
  packages/atom/package.json
  packages/avax/package.json
  packages/btc/package.json
  packages/cryptography/package.json
  packages/dot/package.json
  packages/egld/package.json
  packages/eos/package.json
  packages/eth/package.json
  packages/helpers/package.json
  packages/http-fetch/package.json
  packages/intl/package.json
  packages/lsk/package.json
  packages/luna/package.json
  packages/markets/package.json
  packages/nano/package.json
  packages/neo/package.json
  packages/news/package.json
  packages/profiles/package.json
  packages/sdk/package.json
  packages/sol/package.json
  packages/test/package.json
  packages/trx/package.json
  packages/xlm/package.json
  packages/xrp/package.json
  packages/zil/package.json
Labels: chore

#420 fix(btc): update ledger mocks
  packages/btc/source/key-pair.service.ts
  packages/btc/source/ledger.service.test.ts
  packages/btc/source/ledger.service.ts
  packages/btc/source/transaction.service.ledger.test.ts
  packages/btc/source/transaction.service.ts
  packages/btc/test/fixtures/ledger.ts
Labels: bugfix

#252 feat(btc): add multisignature support
  packages/btc/source/__snapshots__/transaction.service.test.ts.snap
  packages/btc/source/address.domain.ts
  packages/btc/source/address.factory.ts
  packages/btc/source/coin.provider.ts
  packages/btc/source/constants.ts
  packages/btc/source/contracts.ts
  packages/btc/source/helpers.ts
  packages/btc/source/multi-signature.contract.ts
  packages/btc/source/multi-signature.domain.ts
  packages/btc/source/multi-signature.service.test.ts
  packages/btc/source/multi-signature.service.ts
  packages/btc/source/multi-signature.signer.ts
  packages/btc/source/multi-signature.transaction.test.ts
  packages/btc/source/multi-signature.transaction.ts
  packages/btc/source/musig-wallet-data-helper.ts
  packages/btc/source/networks/btc.livenet.ts
  packages/btc/source/networks/btc.testnet.ts
  packages/btc/source/public-key.service.ts
  packages/btc/source/signed-transaction.dto.test.ts
  packages/btc/source/signed-transaction.dto.ts
  packages/btc/source/transaction.service.ledger.test.ts
  packages/btc/source/transaction.service.test.ts
  packages/btc/source/transaction.service.ts
  packages/btc/source/wallet-data-helper.ts
  packages/btc/test/example-musig-signing.test.ts
  packages/btc/test/example-musig-wallet-creation.test.ts
  packages/btc/test/fixtures/musig-legacy-txs.ts
  packages/btc/test/fixtures/musig-native-segwit-txs.ts
  packages/btc/test/fixtures/musig-p2sh-segwit-txs.ts
  packages/profiles/source/__snapshots__/env.test.ts.snap
  packages/profiles/test/fixtures/identity.ts
  packages/profiles/test/mocking.ts
  packages/profiles/test/musig/musig.test.helpers.ts
  packages/sdk/source/services/transaction.contract.ts
Labels: feature

#426 feat(test): implement object matching with `zod`
  .github/workflows/ci.yml
  common/config/rush/browser-approved-packages.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  packages/test/package.json
  packages/test/source/assert.test.js
  packages/test/source/assert.ts
  packages/test/source/index.ts
Labels: feature

#428 chore: require node.js 16 or later
  package.json
  packages/ada/package.json
  packages/ark/package.json
  packages/atom/package.json
  packages/avax/package.json
  packages/btc/package.json
  packages/cryptography/package.json
  packages/dot/package.json
  packages/egld/package.json
  packages/eos/package.json
  packages/eth/package.json
  packages/helpers/package.json
  packages/http-fetch/package.json
  packages/intl/package.json
  packages/lsk/package.json
  packages/luna/package.json
  packages/markets/package.json
  packages/nano/package.json
  packages/neo/package.json
  packages/news/package.json
  packages/profiles/package.json
  packages/sdk/package.json
  packages/sol/package.json
  packages/test/package.json
  packages/test/source/assert.test.js
  packages/test/source/assert.ts
  packages/trx/package.json
  packages/xlm/package.json
  packages/xrp/package.json
  packages/zil/package.json
  rush.json
Labels: chore

#427 feat(test): implement assertion snapshotting
  common/config/rush/browser-approved-packages.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  packages/test/package.json
  packages/test/source/__snapshots__/false.snapshot
  packages/test/source/__snapshots__/hello.snapshot
  packages/test/source/__snapshots__/nan.snapshot
  packages/test/source/__snapshots__/number.snapshot
  packages/test/source/__snapshots__/object.snapshot
  packages/test/source/__snapshots__/true.snapshot
  packages/test/source/assert.test.js
  packages/test/source/assert.ts
Labels: feature

#429 feat(test): implement `describe` for suites
  packages/test/source/describe.test.js
  packages/test/source/describe.ts
Labels: feature

#431 fix(profiles): update currency helper to properly format without ticker
  packages/profiles/source/helpers/currency.test.ts
  packages/profiles/source/helpers/currency.ts
Labels: bugfix

#432 feat(test): implement context for describe
  packages/test/source/describe.test.js
  packages/test/source/describe.ts
Labels: feature

#437 feat(test): implement datasets
  common/config/rush/browser-approved-packages.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  packages/test/package.json
  packages/test/source/describe.test.js
  packages/test/source/describe.ts
  packages/test/source/each.ts
Labels: feature

#438 chore: update TypeScript to 4.5
  .github/workflows/cf.yml
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  packages/ada/package.json
  packages/ark/package.json
  packages/atom/package.json
  packages/avax/package.json
  packages/btc/package.json
  packages/cryptography/package.json
  packages/dot/package.json
  packages/egld/package.json
  packages/eos/package.json
  packages/eth/package.json
  packages/helpers/package.json
  packages/http-fetch/package.json
  packages/intl/package.json
  packages/lsk/package.json
  packages/luna/package.json
  packages/markets/package.json
  packages/nano/package.json
  packages/neo/package.json
  packages/news/package.json
  packages/profiles/package.json
  packages/sdk/package.json
  packages/sol/package.json
  packages/trx/package.json
  packages/xlm/package.json
  packages/xrp/package.json
  packages/zil/package.json
  tsconfig.json
Labels: chore

#441 test(ark): enable fee tests
  .eslintignore
  packages/ark/snapshots/fees-ark-delegateRegistration.snapshot
  packages/ark/snapshots/fees-ark-delegateResignation.snapshot
  packages/ark/snapshots/fees-ark-htlcClaim.snapshot
  packages/ark/snapshots/fees-ark-htlcLock.snapshot
  packages/ark/snapshots/fees-ark-htlcRefund.snapshot
  packages/ark/snapshots/fees-ark-ipfs.snapshot
  packages/ark/snapshots/fees-ark-multiPayment.snapshot
  packages/ark/snapshots/fees-ark-multiSignature.snapshot
  packages/ark/snapshots/fees-ark-secondSignature.snapshot
  packages/ark/snapshots/fees-ark-transfer.snapshot
  packages/ark/snapshots/fees-ark-vote.snapshot
  packages/ark/snapshots/fees-bind-delegateRegistration.snapshot
  packages/ark/snapshots/fees-bind-delegateResignation.snapshot
  packages/ark/snapshots/fees-bind-htlcClaim.snapshot
  packages/ark/snapshots/fees-bind-htlcLock.snapshot
  packages/ark/snapshots/fees-bind-htlcRefund.snapshot
  packages/ark/snapshots/fees-bind-ipfs.snapshot
  packages/ark/snapshots/fees-bind-multiPayment.snapshot
  packages/ark/snapshots/fees-bind-multiSignature.snapshot
  packages/ark/snapshots/fees-bind-secondSignature.snapshot
  packages/ark/snapshots/fees-bind-transfer.snapshot
  packages/ark/snapshots/fees-bind-vote.snapshot
  packages/ark/source/fee.service.test.js
  packages/ark/source/transaction.service.test.js
  packages/test/snapshots/false.snapshot
  packages/test/snapshots/hello.snapshot
  packages/test/snapshots/nan.snapshot
  packages/test/snapshots/number.snapshot
  packages/test/snapshots/object.snapshot
  packages/test/snapshots/true.snapshot
  packages/test/source/assert.ts
Labels: test

#442 test(btc): enable fee tests
  packages/ark/snapshots/fees_ark_delegate_registration.snapshot
  packages/ark/snapshots/fees_ark_delegate_resignation.snapshot
  packages/ark/snapshots/fees_ark_htlc_claim.snapshot
  packages/ark/snapshots/fees_ark_htlc_lock.snapshot
  packages/ark/snapshots/fees_ark_htlc_refund.snapshot
  packages/ark/snapshots/fees_ark_ipfs.snapshot
  packages/ark/snapshots/fees_ark_multi_payment.snapshot
  packages/ark/snapshots/fees_ark_multi_signature.snapshot
  packages/ark/snapshots/fees_ark_second_signature.snapshot
  packages/ark/snapshots/fees_ark_transfer.snapshot
  packages/ark/snapshots/fees_ark_vote.snapshot
  packages/ark/snapshots/fees_bind_delegate_registration.snapshot
  packages/ark/snapshots/fees_bind_delegate_resignation.snapshot
  packages/ark/snapshots/fees_bind_htlc_claim.snapshot
  packages/ark/snapshots/fees_bind_htlc_lock.snapshot
  packages/ark/snapshots/fees_bind_htlc_refund.snapshot
  packages/ark/snapshots/fees_bind_ipfs.snapshot
  packages/ark/snapshots/fees_bind_multi_payment.snapshot
  packages/ark/snapshots/fees_bind_multi_signature.snapshot
  packages/ark/snapshots/fees_bind_second_signature.snapshot
  packages/ark/snapshots/fees_bind_transfer.snapshot
  packages/ark/snapshots/fees_bind_vote.snapshot
  packages/ark/source/fee.service.test.js
  packages/btc/snapshots/fees_delegate_registration.snapshot
  packages/btc/snapshots/fees_delegate_resignation.snapshot
  packages/btc/snapshots/fees_htlc_claim.snapshot
  packages/btc/snapshots/fees_htlc_lock.snapshot
  packages/btc/snapshots/fees_htlc_refund.snapshot
  packages/btc/snapshots/fees_ipfs.snapshot
  packages/btc/snapshots/fees_multi_payment.snapshot
  packages/btc/snapshots/fees_multi_signature.snapshot
  packages/btc/snapshots/fees_second_signature.snapshot
  packages/btc/snapshots/fees_transfer.snapshot
  packages/btc/snapshots/fees_vote.snapshot
  packages/btc/source/fee.service.test.js
Labels: test

#443 test(lsk): fix `DateTime` mocks for client service
  packages/lsk/source/client.service.test.js
Labels: test

#444 test(btc): enable ledger tests for BIP44/49/84
  packages/btc/source/transaction.service.ledger.test.js
  packages/btc/source/transaction.service.test.js
  packages/btc/test/fixtures/ledger.ts
Labels: test

#445 test(sdk): enable network and transaction tests
  packages/ark/source/manifest.ts
  packages/sdk/source/confirmed-transaction.dto.test.js
  packages/sdk/source/network.test.js
Labels: test

#446 test(profiles): enable all WIF tests
  packages/profiles/source/wif.test.js
  packages/test/source/index.ts
Labels: test

#447 test(profiles): enable `each` cases for `TransactionService`
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  packages/profiles/source/wallet-transaction.service.test.js
  packages/profiles/test/mocking.ts
  packages/test/package.json
  packages/test/source/nock.ts
Labels: test

#448 feat(test): log suite hook errors
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  packages/http-fetch/source/request.test.js
  packages/markets/source/drivers/coincap/index.test.js
  packages/markets/source/drivers/coingecko/index.test.js
  packages/markets/source/drivers/cryptocompare/index.test.js
  packages/news/source/blockfolio.test.js
  packages/news/source/feed.test.js
  packages/profiles/source/env.test.js
  packages/profiles/source/transaction.dto.test.js
  packages/profiles/test/mocking.ts
  packages/test/package.json
  packages/test/source/describe.ts
Labels: feature

#450 feat(profiles): add networks filter in portfolio breakdown
  packages/profiles/source/portfolio.contract.ts
  packages/profiles/source/portfolio.test.ts
  packages/profiles/source/portfolio.ts
Labels: feature

#452 refactor(test): expose hooks as standalone and suite functions
  packages/test/source/describe.ts
  packages/test/source/hooks.ts
  packages/test/source/index.ts
Labels: refactor

#453 test(avax): consistent use of `describe`
  packages/avax/source/address.service.test.js
  packages/avax/source/client.service.test.js
  packages/avax/source/key-pair.service.test.js
  packages/avax/source/link.service.test.js
  packages/avax/source/message.service.test.js
  packages/avax/source/private-key.service.test.js
  packages/avax/source/public-key.service.test.js
  packages/avax/source/signed-transaction.dto.test.js
  packages/avax/source/transaction.service.test.js
  packages/avax/source/transaction.service.ts
  packages/test/source/index.ts
Labels: test

#455 test(avax): consistent use of `it`
  packages/avax/source/address.service.test.js
  packages/avax/source/client.service.test.js
  packages/avax/source/key-pair.service.test.js
  packages/avax/source/link.service.test.js
  packages/avax/source/message.service.test.js
  packages/avax/source/private-key.service.test.js
  packages/avax/source/public-key.service.test.js
  packages/avax/source/signed-transaction.dto.test.js
  packages/avax/source/transaction.service.test.js
Labels: test

#459 test(btc): fix failing tests resulting from merge
  packages/btc/snapshots/musig-registration-transaction1.snapshot
  packages/btc/snapshots/musig-registration-transaction2.snapshot
  packages/btc/snapshots/musig-registration-transaction3.snapshot
  packages/btc/source/link.service.test.js
  packages/btc/source/transaction.service.ledger.test.js
  packages/btc/source/transaction.service.test.js
  packages/btc/source/wallet-discovery.service.test.js
  packages/profiles/source/portfolio.test.js
Labels: test

#461 test(ada): consistent use of `describe`
  packages/ada/source/address-list.service.test.js
  packages/ada/source/address.service.test.js
  packages/ada/source/client.service.test.js
  packages/ada/source/extended-public-key.service.test.js
  packages/ada/source/key-pair.service.test.js
  packages/ada/source/link.service.test.js
  packages/ada/source/message.service.test.js
  packages/ada/source/private-key.service.test.js
  packages/ada/source/public-key.service.test.js
  packages/ada/source/signed-transaction.dto.test.js
  packages/ada/source/transaction.dto.test.js
  packages/ada/source/transaction.factory.test.js
  packages/ada/source/transaction.service.test.js
  packages/ada/source/wallet.dto.test.js
Labels: test

#462 test(atom): consistent use of `describe`
  packages/atom/source/address.service.test.js
  packages/atom/source/client.service.test.js
  packages/atom/source/key-pair.service.test.js
  packages/atom/source/ledger.service.test.js
  packages/atom/source/link.service.test.js
  packages/atom/source/message.service.test.js
  packages/atom/source/private-key.service.test.js
  packages/atom/source/public-key.service.test.js
  packages/atom/source/signed-transaction.dto.test.js
  packages/atom/source/transaction.dto.test.js
  packages/atom/source/transaction.service.test.js
  packages/atom/source/wallet.dto.test.js
Labels: test

#464 test(egld): consistent use of `describe`
  packages/egld/source/address.service.test.js
  packages/egld/source/client.service.test.js
  packages/egld/source/key-pair.service.test.js
  packages/egld/source/link.service.test.js
  packages/egld/source/message.service.test.js
  packages/egld/source/private-key.service.test.js
  packages/egld/source/public-key.service.test.js
  packages/egld/source/signed-transaction.dto.test.js
Labels: test

#465 test(eos): consistent use of `describe`
  packages/eos/source/client.service.test.js
  packages/eos/source/ledger.service.test.js
  packages/eos/source/link.service.test.js
  packages/eos/source/message.service.test.js
  packages/eos/source/signed-transaction.dto.test.js
  packages/eos/source/wallet.dto.test.js
Labels: test

#463 test(dot): consistent use of `describe`
  packages/dot/source/address.service.test.js
  packages/dot/source/key-pair.service.test.js
  packages/dot/source/ledger.service.test.js
  packages/dot/source/link.service.test.js
  packages/dot/source/message.service.test.js
  packages/dot/source/private-key.service.test.js
  packages/dot/source/public-key.service.test.js
  packages/dot/source/signed-transaction.dto.test.js
  packages/dot/source/transaction.service.test.js
Labels: test

#467 test(ark): consistent use of describe
  packages/ark/source/address.service.test.js
  packages/ark/source/client.service.test.js
  packages/ark/source/confirmed-transaction.dto.test.js
  packages/ark/source/fee.service.test.js
  packages/ark/source/key-pair.service.test.js
  packages/ark/source/known-wallet.service.test.js
  packages/ark/source/ledger.service.test.js
  packages/ark/source/link.service.test.js
  packages/ark/source/message.service.test.js
  packages/ark/source/multi-signature.service.test.js
  packages/ark/source/private-key.service.test.js
  packages/ark/source/public-key.service.test.js
  packages/ark/source/signed-transaction.dto.test.js
  packages/ark/source/signed-transaction.dto.ts
  packages/ark/source/transaction-type.service.test.js
  packages/ark/source/transaction.service.test.js
  packages/ark/source/wallet.dto.test.js
  packages/ark/source/wif.service.test.js
  packages/test/source/describe.ts
  packages/test/source/index.ts
Labels: test

#468 ci: move `lint` step into `ci` workflow
  .github/workflows/cf.yml
  .github/workflows/ci.yml
  .github/workflows/label.yml
Labels: ci

#469 test(cryptography): consistent use of `describe`
  packages/cryptography/source/aes.test.js
  packages/cryptography/source/argon2.test.js
  packages/cryptography/source/base58-check.test.js
  packages/cryptography/source/base58.test.js
  packages/cryptography/source/base64.test.js
  packages/cryptography/source/bcrypt.test.js
  packages/cryptography/source/bip32.test.js
  packages/cryptography/source/bip38.test.js
  packages/cryptography/source/bip39.test.js
  packages/cryptography/source/bip44.test.js
  packages/cryptography/source/hash.test.js
  packages/cryptography/source/pbkdf2.test.js
  packages/cryptography/source/uuid.test.js
  packages/cryptography/source/wif.test.js
  packages/test/source/describe.ts
Labels: test

#470 test(test): consistent use of `describe`
  .github/workflows/ci.yml
  packages/test/source/assert.test.js
  packages/test/source/describe.test.js
  packages/test/source/describe.ts
Labels: test

#471 test(news): consistent use of `describe`
  packages/news/source/blockfolio.test.js
  packages/news/source/feed.test.js
  packages/test/source/describe.ts
Labels: test

#472 test(markets): consistent use of `describe`
  packages/markets/source/drivers/coincap/index.test.js
  packages/markets/source/drivers/coincap/transformers/historical-price-transformer.test.js
  packages/markets/source/drivers/coincap/transformers/market-transformer.test.js
  packages/markets/source/drivers/coincap/utils.test.js
  packages/markets/source/drivers/coingecko/index.test.js
  packages/markets/source/drivers/coingecko/transformers/historical-price-transformer.test.js
  packages/markets/source/drivers/coingecko/transformers/historical-volume-transformer.test.js
  packages/markets/source/drivers/coingecko/transformers/market-transformer.test.js
  packages/markets/source/drivers/cryptocompare/index.test.js
  packages/markets/source/drivers/cryptocompare/transformers/historical-price-transformer.test.js
  packages/markets/source/drivers/cryptocompare/transformers/historical-volume-transformer.test.js
  packages/markets/source/drivers/cryptocompare/transformers/market-transformer.test.js
  packages/markets/source/index.test.js
Labels: test

#473 test(http-fetch): consistent use of `describe`
  packages/http-fetch/source/request.test.js
Labels: test

#474 test(intl): consistent use of `describe`
  packages/intl/snapshots/currencies.snapshot
  packages/intl/source/currencies.test.js
  packages/intl/source/currency.test.js
  packages/intl/source/datetime.test.js
  packages/intl/source/money.test.js
  packages/intl/source/numeral.test.js
Labels: test

#479 chore: update development dependencies
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  packages/ada/package.json
  packages/ark/package.json
  packages/atom/package.json
  packages/avax/package.json
  packages/btc/package.json
  packages/cryptography/package.json
  packages/dot/package.json
  packages/egld/package.json
  packages/eos/package.json
  packages/eth/package.json
  packages/helpers/package.json
  packages/http-fetch/package.json
  packages/intl/package.json
  packages/lsk/package.json
  packages/luna/package.json
  packages/markets/package.json
  packages/nano/package.json
  packages/neo/package.json
  packages/news/package.json
  packages/profiles/package.json
  packages/sdk/package.json
  packages/sol/package.json
  packages/test/package.json
  packages/trx/package.json
  packages/xlm/package.json
  packages/xrp/package.json
  packages/zil/package.json
Labels: chore

#481 test(profiles): run integration tests as part of CI
  .github/workflows/ci.yml
  packages/profiles/package.json
  packages/profiles/test/integration/ark.musig.registration.test.js
  packages/profiles/test/integration/btc-wallets.test.js
  packages/profiles/test/integration/lsk.musig.registration.test.js
  packages/profiles/test/integration/musig.test.helpers.ts
  packages/profiles/test/musig/ark.musig.registration.test.js
  packages/profiles/test/musig/lsk.musig.registration.test.js
Labels: test

#482 test(zil): consistent use of `describe`
  packages/zil/source/address.service.test.js
  packages/zil/source/client.service.test.js
  packages/zil/source/key-pair.service.test.js
  packages/zil/source/link.service.test.js
  packages/zil/source/private-key.service.test.js
  packages/zil/source/public-key.service.test.js
  packages/zil/source/signed-transaction.dto.test.js
  packages/zil/source/transaction.service.test.js
Labels: test

#483 test(sol): consistent use of `describe`
  packages/sol/source/address.service.test.js
  packages/sol/source/key-pair.service.test.js
  packages/sol/source/link.service.test.js
  packages/sol/source/private-key.service.test.js
  packages/sol/source/public-key.service.test.js
  packages/sol/source/signed-transaction.dto.test.js
Labels: test

#484 test(trx): consistent use of `describe`
  packages/trx/source/address.service.test.js
  packages/trx/source/client.service.test.js
  packages/trx/source/key-pair.service.test.js
  packages/trx/source/ledger.service.test.js
  packages/trx/source/link.service.test.js
  packages/trx/source/message.service.test.js
  packages/trx/source/private-key.service.test.js
  packages/trx/source/public-key.service.test.js
  packages/trx/source/signed-transaction.dto.test.js
  packages/trx/source/transaction.dto.test.js
  packages/trx/source/transaction.service.test.js
  packages/trx/source/wallet.dto.test.js
  packages/trx/source/wif.service.test.js
Labels: test

#485 test(xlm): consistent use of `describe`
  packages/xlm/source/address.service.test.js
  packages/xlm/source/client.service.test.js
  packages/xlm/source/keys.service.test.js
  packages/xlm/source/ledger.service.test.js
  packages/xlm/source/link.service.test.js
  packages/xlm/source/message.service.test.js
  packages/xlm/source/private-key.service.test.js
  packages/xlm/source/public-key.service.test.js
  packages/xlm/source/signed-transaction.dto.test.js
  packages/xlm/source/transaction.service.test.js
  packages/xlm/source/wallet.dto.test.js
Labels: test

#487 test: remove unnecessary `disableNetConnect` calls
  packages/ada/source/client.service.test.js
  packages/ada/source/transaction.service.test.js
  packages/ark/source/client.service.test.js
  packages/atom/source/client.service.test.js
  packages/atom/source/transaction.service.test.js
  packages/btc/source/client.service.test.js
  packages/btc/source/multi-signature.service.test.ts
  packages/btc/source/multi-signature.transaction.test.ts
  packages/btc/source/musig-wallet-data-helper.test.js
  packages/btc/source/transaction.service.test.js
  packages/btc/source/wallet-data-helper.test.js
  packages/btc/test/example-musig-signing.test.ts
  packages/btc/test/example-musig-wallet-creation.test.ts
  packages/egld/source/client.service.test.js
  packages/eos/source/client.service.test.js
  packages/eth/source/client.service.test.js
  packages/lsk/source/client.service.test.js
  packages/lsk/source/fee.service.test.js
  packages/lsk/source/multi-signature.service.test.js
  packages/lsk/source/transaction.service.test.js
  packages/nano/source/client.service.test.js
  packages/nano/source/transaction.service.test.js
  packages/neo/source/client.service.test.js
  packages/profiles/source/coin.service.test.js
  packages/profiles/source/delegate-syncer.service.test.js
  packages/profiles/source/delegate.service.test.js
  packages/profiles/source/env.test.js
  packages/profiles/source/fee.service.test.js
  packages/profiles/source/known-wallet.service.test.js
  packages/profiles/source/notification.service.test.js
  packages/profiles/source/notification.transactions.service.test.js
  packages/profiles/source/plugin-registry.service.test.js
  packages/profiles/source/portfolio.test.js
  packages/profiles/source/profile.dumper.test.js
  packages/profiles/source/profile.importer.test.js
  packages/profiles/source/profile.initialiser.test.js
  packages/profiles/source/profile.repository.test.js
  packages/profiles/source/profile.serialiser.test.js
  packages/profiles/source/profile.test.js
  packages/profiles/source/profile.validator.test.js
  packages/profiles/source/transaction.aggregate.test.js
  packages/profiles/source/transaction.dto.test.js
  packages/profiles/source/transaction.mapper.test.js
  packages/profiles/source/wallet.factory.test.js
  packages/profiles/source/wallet.identifier.factory.test.js
  packages/profiles/source/wallet.test.js
  packages/profiles/source/wif.test.js
  packages/sdk/source/coin-factory.test.js
  packages/sdk/source/coin.test.js
  packages/trx/source/client.service.test.js
  packages/trx/source/transaction.service.test.js
  packages/xlm/source/client.service.test.js
  packages/xlm/source/transaction.service.test.js
  packages/zil/source/client.service.test.js
Labels: test

#486 refactor(test): always clean nock mocks in `after` hooks
  packages/ark/source/client.service.test.js
  packages/ark/source/fee.service.test.js
  packages/ark/source/known-wallet.service.test.js
  packages/ark/source/ledger.service.test.js
  packages/ark/source/multi-signature.service.test.js
  packages/ark/source/transaction.service.test.js
  packages/lsk/source/ledger.service.test.js
  packages/news/source/blockfolio.test.js
  packages/profiles/test/integration/ark.musig.registration.test.js
  packages/profiles/test/integration/lsk.musig.registration.test.js
  packages/test/source/describe.ts
  packages/xlm/source/client.service.test.js
  packages/xlm/source/transaction.service.test.js
  packages/zil/source/client.service.test.js
Labels: refactor

#488 refactor(test): use `uvu` hooks to manage nock lifecycle
  packages/avax/source/client.service.test.js
  packages/test/source/describe.ts
  packages/test/source/nock.ts
Labels: refactor

#491 test(xrp): consistent use of `describe`
  packages/xrp/source/address.service.test.js
  packages/xrp/source/client.service.test.js
  packages/xrp/source/key-pair.service.test.js
  packages/xrp/source/ledger.service.test.js
  packages/xrp/source/link.service.test.js
  packages/xrp/source/message.service.test.js
  packages/xrp/source/signed-transaction.dto.test.js
  packages/xrp/source/transaction.dto.test.js
  packages/xrp/source/wallet.dto.test.js
Labels: test

#490 chore(ada): update `@emurgo/cardano-serialization-lib-nodejs` to next major
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  packages/ada/package.json
  packages/ada/source/client.service.test.js
  packages/ada/source/networks/ada.mainnet.ts
  packages/ada/source/networks/ada.testnet.ts
  packages/ada/source/transaction.service.test.js
  packages/ada/source/transaction.service.ts
  packages/ada/test/fixtures/transaction/expiration.json
  packages/ada/test/fixtures/transaction/utxos.json
  packages/ada/test/mariano.test.js
  packages/ada/test/submit-tx.test.js
  packages/luna/package.json
  packages/nano/package.json
Labels: chore

#496 test(neo): consistent use of `describe`
  packages/neo/source/address.service.test.js
  packages/neo/source/client.service.test.js
  packages/neo/source/key-pair.service.test.js
  packages/neo/source/ledger.service.test.js
  packages/neo/source/link.service.test.js
  packages/neo/source/message.service.test.js
  packages/neo/source/private-key.service.test.js
  packages/neo/source/public-key.service.test.js
  packages/neo/source/signed-transaction.dto.test.js
  packages/neo/source/transaction.dto.test.js
  packages/neo/source/wallet.dto.test.js
  packages/neo/source/wif.service.test.js
Labels: test

#497 test(luna): consistent use of `describe`
  packages/luna/source/link.service.test.js
Labels: test

#495 test(nano): consistent use of `describe`
  packages/nano/source/client.service.test.js
  packages/nano/source/link.service.test.js
  packages/nano/source/message.service.test.js
  packages/nano/source/signed-transaction.dto.test.js
  packages/nano/source/transaction.service.test.js
Labels: test

#501 test(sdk): consistent use of `describe`
  packages/sdk/snapshots/enums-feature-flags.snapshot
  packages/sdk/source/big-number.service.test.js
  packages/sdk/source/big-number.test.js
  packages/sdk/source/coin-factory.test.js
  packages/sdk/source/coin.test.js
  packages/sdk/source/config.test.js
  packages/sdk/source/confirmed-transaction.dto.test.js
  packages/sdk/source/container.test.js
  packages/sdk/source/enums.test.js
  packages/sdk/source/exceptions.test.js
  packages/sdk/source/helpers.test.js
  packages/sdk/source/http-exceptions.test.js
  packages/sdk/source/http-request.test.js
  packages/sdk/source/http-response.test.js
  packages/sdk/source/http-urls.test.js
  packages/sdk/source/manifest.test.js
  packages/sdk/source/network-repository.test.js
  packages/sdk/source/network.test.js
  packages/sdk/source/paginator.test.js
  packages/sdk/source/signatory.test.js
  packages/sdk/source/signed-transaction.dto.test.js
  packages/sdk/source/transactions.collection.test.js
  packages/sdk/source/unspent-transaction.dto.test.js
  packages/sdk/source/wallet.dto.test.js
  packages/sdk/source/wallets.collection.test.js
Labels: test

#504 refactor: expose `bech32` through `cryptography` package
  packages/ada/package.json
  packages/ada/source/address.service.ts
  packages/atom/package.json
  packages/atom/source/address.service.ts
  packages/cryptography/package.json
  packages/cryptography/source/index.ts
  packages/egld/package.json
  packages/egld/source/address.service.ts
  pnpm-lock.yaml
Labels: refactor

#507 docs: add details for testing with uvu
  TESTING.md
Labels: docs

#505 test(lsk): consistent use of `describe`
  packages/lsk/source/address.service.test.js
  packages/lsk/source/asset.serializer.test.js
  packages/lsk/source/client.service.test.js
  packages/lsk/source/fee.service.test.js
  packages/lsk/source/key-pair.service.test.js
  packages/lsk/source/ledger.service.test.js
  packages/lsk/source/link.service.test.js
  packages/lsk/source/message.service.test.js
  packages/lsk/source/multi-signature.service.test.js
  packages/lsk/source/multi-signature.transaction.test.js
  packages/lsk/source/private-key.service.test.js
  packages/lsk/source/public-key.service.test.js
  packages/lsk/source/signed-transaction.dto.test.js
  packages/lsk/source/transaction.dto.test.js
  packages/lsk/source/transaction.serializer.test.js
  packages/lsk/source/transaction.service.test.js
  packages/lsk/source/wallet.dto.test.js
  packages/lsk/source/wif.service.test.js
  packages/test/source/each.ts
Labels: test

#510 fix(test): export `describeWithContext`
  packages/test/source/index.ts
Labels: chore

#509 chore: add `typesync` script
  TESTING.md
  packages/ada/package.json
  packages/ark/package.json
  packages/atom/package.json
  packages/avax/package.json
  packages/btc/package.json
  packages/cryptography/package.json
  packages/dot/package.json
  packages/egld/package.json
  packages/eos/package.json
  packages/eth/package.json
  packages/helpers/package.json
  packages/http-fetch/package.json
  packages/lsk/package.json
  packages/luna/package.json
  packages/nano/package.json
  packages/neo/package.json
  packages/profiles/package.json
  packages/sdk/package.json
  packages/sol/package.json
  packages/test/package.json
  packages/test/source/assert.ts
  packages/test/source/describe.ts
  packages/test/source/mockery.ts
  packages/trx/package.json
  packages/xlm/package.json
  packages/xrp/package.json
  packages/zil/package.json
  pnpm-lock.yaml
  scripts/types.sh
Labels: chore

#511 test(eth): consistent use of `describe` and `context`
  packages/eth/source/address.service.test.js
  packages/eth/source/client.service.test.js
  packages/eth/source/fee.service.test.js
  packages/eth/source/key-pair.service.test.js
  packages/eth/source/ledger.service.test.js
  packages/eth/source/link.service.test.js
  packages/eth/source/private-key.service.test.js
  packages/eth/source/transaction.dto.test.js
  packages/eth/source/wallet.dto.test.js
Labels: test

#512 test(btc): consistent use of `describe` and `context`
  packages/btc/source/address.domain.test.js
  packages/btc/source/address.service.test.js
  packages/btc/source/client.service.test.js
  packages/btc/source/fee.service.test.js
  packages/btc/source/key-pair.service.test.js
  packages/btc/source/link.service.test.js
  packages/btc/source/message.service.test.js
  packages/btc/source/musig-wallet-data-helper.test.js
  packages/btc/source/private-key.service.test.js
  packages/btc/source/public-key.service.test.js
  packages/btc/source/transaction.dto.test.js
  packages/btc/source/transaction.service.ledger.test.js
  packages/btc/source/transaction.service.test.js
  packages/btc/source/wallet-data-helper.test.js
  packages/btc/source/wallet-discovery.service.test.js
  packages/btc/source/wallet.dto.test.js
  packages/btc/source/wif.service.test.js
Labels: test

#513 test(zil): consistent use of `context`
  packages/zil/source/address.service.test.js
  packages/zil/source/client.service.test.js
  packages/zil/source/key-pair.service.test.js
  packages/zil/source/link.service.test.js
  packages/zil/source/private-key.service.test.js
  packages/zil/source/public-key.service.test.js
  packages/zil/source/signed-transaction.dto.test.js
  packages/zil/source/transaction.service.test.js
Labels: test

#515 test(xlm): consistent use of `context`
  packages/xlm/source/address.service.test.js
  packages/xlm/source/client.service.test.js
  packages/xlm/source/keys.service.test.js
  packages/xlm/source/link.service.test.js
  packages/xlm/source/message.service.test.js
  packages/xlm/source/private-key.service.test.js
  packages/xlm/source/public-key.service.test.js
  packages/xlm/source/signed-transaction.dto.test.js
  packages/xlm/source/transaction.service.test.js
  packages/xlm/source/wallet.dto.test.js
Labels: test

#516 test(sol): consistent use of `context`
  packages/sol/source/address.service.test.js
  packages/sol/source/key-pair.service.test.js
  packages/sol/source/link.service.test.js
  packages/sol/source/private-key.service.test.js
  packages/sol/source/public-key.service.test.js
  packages/sol/source/signed-transaction.dto.test.js
Labels: test

#525 test(lsk): consistent use of `context`
  packages/lsk/source/address.service.test.js
  packages/lsk/source/client.service.test.js
  packages/lsk/source/fee.service.test.js
  packages/lsk/source/key-pair.service.test.js
  packages/lsk/source/link.service.test.js
  packages/lsk/source/message.service.test.js
  packages/lsk/source/multi-signature.service.test.js
  packages/lsk/source/private-key.service.test.js
  packages/lsk/source/public-key.service.test.js
  packages/lsk/source/signed-transaction.dto.test.js
  packages/lsk/source/transaction.dto.test.js
  packages/lsk/source/transaction.service.test.js
  packages/lsk/source/wallet.dto.test.js
  packages/lsk/source/wif.service.test.js
Labels: test

#524 test(luna): consistent use of `context`
  packages/luna/source/link.service.test.js
Labels: test

#523 test(markets): consistent use of `context`
  packages/markets/source/drivers/coincap/index.test.js
  packages/markets/source/drivers/coincap/transformers/historical-price-transformer.test.js
  packages/markets/source/drivers/coincap/transformers/market-transformer.test.js
  packages/markets/source/drivers/coingecko/index.test.js
  packages/markets/source/drivers/coingecko/transformers/historical-volume-transformer.test.js
  packages/markets/source/drivers/coingecko/transformers/market-transformer.test.js
  packages/markets/source/drivers/cryptocompare/index.test.js
  packages/markets/source/drivers/cryptocompare/transformers/historical-price-transformer.test.js
  packages/markets/source/drivers/cryptocompare/transformers/historical-volume-transformer.test.js
  packages/markets/source/drivers/cryptocompare/transformers/market-transformer.test.js
  packages/markets/source/index.test.js
Labels: test

#521 test(news): consistent use of `context`
  packages/news/source/blockfolio.test.js
  packages/news/source/feed.test.js
Labels: test

#522 test(nano): consistent use of `context`
  packages/nano/source/client.service.test.js
  packages/nano/source/link.service.test.js
  packages/nano/source/message.service.test.js
  packages/nano/source/signed-transaction.dto.test.js
  packages/nano/source/transaction.service.test.js
Labels: test

#519 test(neo): consistent use of `context`
  packages/neo/source/address.service.test.js
  packages/neo/source/client.service.test.js
  packages/neo/source/key-pair.service.test.js
  packages/neo/source/link.service.test.js
  packages/neo/source/message.service.test.js
  packages/neo/source/private-key.service.test.js
  packages/neo/source/public-key.service.test.js
  packages/neo/source/signed-transaction.dto.test.js
  packages/neo/source/transaction.dto.test.js
  packages/neo/source/wallet.dto.test.js
  packages/neo/source/wif.service.test.js
Labels: test

#518 test(sdk): consistent use of `context`
  packages/sdk/source/coin-factory.test.js
  packages/sdk/source/coin.test.js
  packages/sdk/source/config.test.js
  packages/sdk/source/http-request.test.js
  packages/sdk/source/http-response.test.js
  packages/sdk/source/manifest.test.js
  packages/sdk/source/network-repository.test.js
  packages/sdk/source/network.test.js
  packages/sdk/source/paginator.test.js
  packages/sdk/source/transactions.collection.test.js
  packages/sdk/source/wallets.collection.test.js
Labels: test

#526 refactor: use `describeWithContext` when appropriate
  packages/lsk/source/transaction.service.test.js
  packages/markets/source/drivers/coincap/index.test.js
  packages/markets/source/drivers/coingecko/index.test.js
  packages/markets/source/drivers/cryptocompare/index.test.js
  packages/sdk/source/coin.test.js
Labels: refactor

#535 test(intl): consistent use of `context`
  packages/intl/source/datetime.test.js
  packages/intl/source/money.test.js
Labels: test

#538 test(eos): consistent use of `context`
  packages/eos/source/client.service.test.js
  packages/eos/source/link.service.test.js
  packages/eos/source/message.service.test.js
  packages/eos/source/signed-transaction.dto.test.js
  packages/eos/source/wallet.dto.test.js
Labels: test

#537 test(helpers): consistent use of `context`
  packages/helpers/source/assign.test.js
  packages/helpers/source/bignumber.test.js
  packages/helpers/source/censor.test.js
  packages/helpers/source/collection.test.js
  packages/helpers/source/find.test.js
  packages/helpers/source/has-some-property.test.js
  packages/helpers/source/immutable/order-by.test.js
  packages/helpers/source/immutable/sort-by-desc.test.js
  packages/helpers/source/immutable/sort-by.test.js
  packages/helpers/source/is-enumerable.test.js
  packages/helpers/source/key-by.test.js
  packages/helpers/source/lower-first.test.js
  packages/helpers/source/map-values.test.js
  packages/helpers/source/order-by.test.js
  packages/helpers/source/partition.test.js
  packages/helpers/source/reject.test.js
  packages/helpers/source/sort-by-desc.test.js
  packages/helpers/source/sort-by.test.js
  packages/helpers/source/upper-first.test.js
  packages/helpers/source/uri.test.js
  packages/helpers/source/validator.test.js
Labels: test

#539 test(egld): consistent use of `context`
  packages/egld/source/address.service.test.js
  packages/egld/source/client.service.test.js
  packages/egld/source/key-pair.service.test.js
  packages/egld/source/link.service.test.js
  packages/egld/source/message.service.test.js
  packages/egld/source/private-key.service.test.js
  packages/egld/source/public-key.service.test.js
  packages/egld/source/signed-transaction.dto.test.js
Labels: test

#536 test(http-fetch): consistent use of `context`
  packages/http-fetch/source/request.test.js
Labels: test

#534 test(trx): consistent use of `context`
  packages/trx/source/address.service.test.js
  packages/trx/source/client.service.test.js
  packages/trx/source/key-pair.service.test.js
  packages/trx/source/link.service.test.js
  packages/trx/source/message.service.test.js
  packages/trx/source/private-key.service.test.js
  packages/trx/source/public-key.service.test.js
  packages/trx/source/signed-transaction.dto.test.js
  packages/trx/source/transaction.dto.test.js
  packages/trx/source/transaction.service.test.js
  packages/trx/source/wallet.dto.test.js
  packages/trx/source/wif.service.test.js
Labels: test

#540 test(dot): consistent use of `context`
  packages/dot/source/address.service.test.js
  packages/dot/source/key-pair.service.test.js
  packages/dot/source/link.service.test.js
  packages/dot/source/message.service.test.js
  packages/dot/source/private-key.service.test.js
  packages/dot/source/public-key.service.test.js
  packages/dot/source/signed-transaction.dto.test.js
  packages/dot/source/transaction.service.test.js
Labels: test

#543 test(atom): consistent use of `context`
  packages/atom/source/address.service.test.js
  packages/atom/source/client.service.test.js
  packages/atom/source/key-pair.service.test.js
  packages/atom/source/link.service.test.js
  packages/atom/source/message.service.test.js
  packages/atom/source/private-key.service.test.js
  packages/atom/source/public-key.service.test.js
  packages/atom/source/signed-transaction.dto.test.js
  packages/atom/source/transaction.dto.test.js
  packages/atom/source/transaction.service.test.js
  packages/atom/source/wallet.dto.test.js
Labels: test

#541 test(cryptography): consistent use of `context`
  packages/cryptography/source/aes.test.js
  packages/cryptography/source/base64.test.js
  packages/cryptography/source/bip32.test.js
  packages/cryptography/source/bip38.test.js
  packages/cryptography/source/bip39.test.js
  packages/cryptography/source/pbkdf2.test.js
  packages/cryptography/source/uuid.test.js
Labels: test

#542 test(avax): consistent use of `context`
  packages/avax/source/address.service.test.js
  packages/avax/source/client.service.test.js
  packages/avax/source/key-pair.service.test.js
  packages/avax/source/link.service.test.js
  packages/avax/source/message.service.test.js
  packages/avax/source/private-key.service.test.js
  packages/avax/source/public-key.service.test.js
  packages/avax/source/signed-transaction.dto.test.js
  packages/avax/source/transaction.service.test.js
Labels: test

#544 test(ark): consistent use of `context`
  packages/ark/source/address.service.test.js
  packages/ark/source/client.service.test.js
  packages/ark/source/confirmed-transaction.dto.test.js
  packages/ark/source/fee.service.test.js
  packages/ark/source/key-pair.service.test.js
  packages/ark/source/known-wallet.service.test.js
  packages/ark/source/message.service.test.js
  packages/ark/source/multi-signature.service.test.js
  packages/ark/source/private-key.service.test.js
  packages/ark/source/public-key.service.test.js
  packages/ark/source/signed-transaction.dto.test.js
  packages/ark/source/transaction.service.test.js
  packages/ark/source/wallet.dto.test.js
  packages/ark/source/wif.service.test.js
Labels: test

#545 test(ada): consistent use of `context`
  packages/ada/source/address-list.service.test.js
  packages/ada/source/address.service.test.js
  packages/ada/source/client.service.test.js
  packages/ada/source/extended-public-key.service.test.js
  packages/ada/source/key-pair.service.test.js
  packages/ada/source/link.service.test.js
  packages/ada/source/message.service.test.js
  packages/ada/source/private-key.service.test.js
  packages/ada/source/public-key.service.test.js
  packages/ada/source/signed-transaction.dto.test.js
  packages/ada/source/transaction.dto.test.js
  packages/ada/source/transaction.service.test.js
  packages/ada/source/wallet.dto.test.js
Labels: test

#551 refactor: replace `test` with `it`
  packages/btc/source/extended-public-key.service.test.js
  packages/btc/source/ledger.service.test.js
  packages/btc/source/multi-signature.service.test.ts
  packages/btc/source/signed-transaction.dto.test.js
  packages/btc/source/signed-transaction.dto.test.ts
  packages/profiles/source/exchange-transaction.repository.test.js
  packages/profiles/source/helpers/attribute-bag.test.js
  packages/profiles/source/setting.repository.test.js
  packages/profiles/source/transaction-index.test.js
  packages/profiles/source/transaction.collection.test.js
  packages/profiles/source/transaction.dto.test.js
  packages/profiles/source/wallet-transaction.service.test.js
  packages/profiles/source/wallet.aggregate.test.js
  packages/profiles/source/wallet.factory.test.js
  packages/profiles/source/wallet.gate.test.js
  packages/profiles/source/wallet.mutator.test.js
  packages/profiles/source/wallet.repository.test.js
  packages/profiles/source/wallet.service.test.js
Labels: refactor

#530 chore(test): sinon types and method order
  packages/test/source/describe.ts
  packages/test/source/mockery.ts
Labels: chore

#549 feat(test): track and restore stubs after every test
  packages/lsk/source/client.service.test.js
  packages/lsk/source/multi-signature.service.test.js
  packages/lsk/source/transaction.service.test.js
  packages/profiles/source/coin.service.test.js
  packages/profiles/source/exchange-rate.service.test.js
  packages/profiles/source/exchange-transaction.repository.test.js
  packages/profiles/source/exchange-transaction.test.js
  packages/profiles/source/multi-signature.test.js
  packages/profiles/source/profile.repository.test.js
  packages/profiles/source/profile.test.js
  packages/profiles/source/serialiser.test.js
  packages/profiles/source/transaction.aggregate.test.js
  packages/profiles/source/transaction.dto.test.js
  packages/profiles/source/wallet-transaction.service.test.js
  packages/profiles/source/wallet.aggregate.test.js
  packages/profiles/source/wallet.factory.test.js
  packages/profiles/source/wallet.identifier.factory.test.js
  packages/profiles/source/wallet.service.test.js
  packages/profiles/source/wallet.synchroniser.test.js
  packages/profiles/source/wallet.test.js
  packages/sdk/source/confirmed-transaction.dto.test.js
  packages/sdk/source/http-response.test.js
  packages/test/source/describe.ts
  packages/test/source/stub.ts
Labels: feature

#556 refactor(test): add types for `describe` methods
  packages/test/source/describe.ts
Labels: test

#554 chore: move all documents into a `docs` folder
  README.md
  cliff.toml
  docs/DEVELOPMENT.md
  docs/NAMING_CONVENTIONS.md
  docs/TESTING.md
  docs/UPGRADING.md
Labels: docs

#552 test(profiles): consistent use of `context`
  packages/profiles/source/helpers/attribute-bag.test.js
  packages/profiles/source/serialiser.test.ts
  packages/profiles/source/setting.repository.test.ts
  packages/profiles/source/signatory.factory.test.ts
  packages/profiles/source/transaction-index.test.ts
  packages/profiles/source/transaction.aggregate.test.ts
  packages/profiles/source/transaction.collection.test.ts
  packages/profiles/source/transaction.dto.test.ts
  packages/profiles/source/transaction.mapper.test.ts
  packages/profiles/source/vote-registry.test.ts
  packages/profiles/source/wallet-transaction.service.test.ts
  packages/profiles/source/wallet.aggregate.test.ts
  packages/profiles/source/wallet.factory.test.ts
  packages/profiles/source/wallet.gate.test.ts
  packages/profiles/source/wallet.identifier.factory.test.ts
  packages/profiles/source/wallet.mutator.test.ts
  packages/profiles/source/wallet.repository.test.ts
  packages/profiles/source/wallet.service.test.ts
  packages/profiles/source/wallet.synchroniser.test.ts
  packages/profiles/source/wallet.test.ts
  packages/profiles/source/wif.test.ts
  packages/test/source/describe.ts
  packages/test/source/nock.ts
Labels: test

#558 feat(avax): implement address validation
  packages/avax/source/address.service.ts
  packages/avax/source/networks/avax.mainnet.ts
Labels: feature

#561 chore: add release commands
  .github/workflows/cdd.yml
  .github/workflows/cdm.yml
  package.json
  packages/ada/package.json
  packages/ark/package.json
  packages/atom/package.json
  packages/avax/package.json
  packages/btc/package.json
  packages/cryptography/package.json
  packages/dot/package.json
  packages/egld/package.json
  packages/eos/package.json
  packages/eth/package.json
  packages/helpers/package.json
  packages/http-fetch/package.json
  packages/intl/package.json
  packages/lsk/package.json
  packages/luna/package.json
  packages/markets/package.json
  packages/nano/package.json
  packages/neo/package.json
  packages/news/package.json
  packages/profiles/package.json
  packages/sdk/package.json
  packages/sol/package.json
  packages/test/package.json
  packages/trx/package.json
  packages/xlm/package.json
  packages/xrp/package.json
  packages/zil/package.json
Labels: chore

#565 refactor(zil): move chain IDs into manifests
  packages/zil/source/networks/zil.mainnet.ts
  packages/zil/source/networks/zil.testnet.ts
  packages/zil/source/zilliqa.ts
Labels: refactor

#569 chore(profiles): expose `ExchangeTransaction` and `ReadOnlyWallet`
  packages/profiles/source/index.ts
Labels: chore
