Repository ArkEcosystem/payvo-sdk, pull requests merged in 2021-12, with the labels that each got.

#584 refactor(ark): remove unused code to reduce bundle size
  packages/ark/source/crypto/crypto/index.ts
  packages/ark/source/crypto/hash.ts
  packages/ark/source/crypto/identities/address.test.ts
  packages/ark/source/crypto/identities/address.ts
  packages/ark/source/crypto/identities/helpers.ts
  packages/ark/source/crypto/identities/keys.ts
  packages/ark/source/crypto/identities/wif.ts
  packages/ark/source/crypto/index.ts
  packages/ark/source/crypto/interfaces/crypto.ts
  packages/ark/source/crypto/interfaces/index.ts
  packages/ark/source/crypto/interfaces/message.ts
  packages/ark/source/crypto/interfaces/networks.ts
  packages/ark/source/crypto/interfaces/transactions.ts
  packages/ark/source/crypto/managers/config.ts
  packages/ark/source/crypto/networks/devnet/exceptions.json
  packages/ark/source/crypto/networks/devnet/index.ts
  packages/ark/source/crypto/networks/index.ts
  packages/ark/source/crypto/networks/mainnet/exceptions.json
  packages/ark/source/crypto/networks/mainnet/index.ts
  packages/ark/source/crypto/networks/testnet/exceptions.json
  packages/ark/source/crypto/networks/testnet/index.ts
  packages/ark/source/crypto/networks/testnet/milestones.json
  packages/ark/source/crypto/networks/testnet/network.json
  packages/ark/source/crypto/transactions/builders/delegate-registration.ts
  packages/ark/source/crypto/transactions/builders/delegate-resignation.ts
  packages/ark/source/crypto/transactions/builders/index.ts
  packages/ark/source/crypto/transactions/builders/ipfs.ts
  packages/ark/source/crypto/transactions/builders/multi-payment.ts
  packages/ark/source/crypto/transactions/builders/multi-signature.ts
  packages/ark/source/crypto/transactions/builders/second-signature.ts
  packages/ark/source/crypto/transactions/builders/transaction.ts
  packages/ark/source/crypto/transactions/builders/transfer.ts
  packages/ark/source/crypto/transactions/builders/vote.ts
  packages/ark/source/crypto/transactions/signer.ts
  packages/ark/source/crypto/transactions/types/multi-payment.ts
  packages/ark/source/crypto/transactions/types/schemas.ts
  packages/ark/source/crypto/transactions/types/transfer.ts
  packages/ark/source/crypto/transactions/utils.ts
  packages/ark/source/crypto/transactions/verifier.ts
  packages/ark/source/crypto/types.ts
  packages/ark/source/crypto/validation/index.ts
  packages/ark/source/crypto/validation/keywords.ts
  packages/ark/source/crypto/validation/schemas.ts
  packages/ark/source/message.service.ts
  packages/ark/source/multi-signature.transaction.ts
Labels: refactor

#587 refactor: reduce duplication in DTOs
  packages/ada/source/confirmed-transaction.dto.ts
  packages/ada/source/wallet.dto.ts
  packages/ark/source/wallet.dto.ts
  packages/atom/source/confirmed-transaction.dto.ts
  packages/atom/source/wallet.dto.ts
  packages/avax/source/wallet.dto.ts
  packages/btc/source/wallet.dto.ts
  packages/dot/source/link.service.test.ts
  packages/dot/source/wallet.dto.ts
  packages/egld/source/confirmed-transaction.dto.ts
  packages/egld/source/wallet.dto.ts
  packages/eos/source/confirmed-transaction.dto.ts
  packages/eos/source/wallet.dto.ts
  packages/eth/source/confirmed-transaction.dto.ts
  packages/eth/source/wallet.dto.ts
  packages/lsk/source/wallet.dto.ts
  packages/luna/source/confirmed-transaction.dto.ts
  packages/luna/source/signed-transaction.dto.ts
  packages/luna/source/wallet.dto.ts
  packages/nano/source/confirmed-transaction.dto.ts
  packages/nano/source/signed-transaction.dto.ts
  packages/nano/source/wallet.dto.ts
  packages/neo/source/confirmed-transaction.dto.ts
  packages/neo/source/wallet.dto.test.ts
  packages/neo/source/wallet.dto.ts
  packages/sdk/source/confirmed-transaction.dto.ts
  packages/sdk/source/signed-transaction.dto.ts
  packages/sdk/source/wallet.dto.ts
  packages/sol/source/confirmed-transaction.dto.ts
  packages/sol/source/wallet.dto.ts
  packages/trx/source/confirmed-transaction.dto.ts
  packages/trx/source/signed-transaction.dto.ts
  packages/trx/source/wallet.dto.test.ts
  packages/trx/source/wallet.dto.ts
  packages/xlm/source/confirmed-transaction.dto.ts
  packages/xlm/source/wallet.dto.ts
  packages/xrp/source/confirmed-transaction.dto.ts
  packages/xrp/source/wallet.dto.ts
  packages/zil/source/wallet.dto.ts
Labels: refactor

#591 chore: swap and adjust some dependencies
  packages/atom/source/crypto.ts
  packages/atom/source/hash.ts
  packages/atom/source/key-pair.service.ts
  packages/atom/source/message.service.ts
  packages/avax/source/message.service.ts
  packages/eos/source/transaction.service.ts
  packages/helpers/source/extension.test.ts
  packages/helpers/source/extension.ts
  packages/helpers/source/index.ts
  packages/helpers/source/parse-git-url.test.ts
  packages/helpers/source/parse-git-url.ts
  packages/helpers/source/random-base64.test.ts
  packages/helpers/source/random-base64.ts
  packages/helpers/source/random-bits.test.ts
  packages/helpers/source/random-bits.ts
  packages/helpers/source/random-hex.test.ts
  packages/helpers/source/random-hex.ts
  packages/helpers/source/sleep.test.ts
  packages/helpers/source/sleep.ts
  packages/http-fetch/package.json
  packages/http-fetch/source/request.ts
  pnpm-lock.yaml
  scripts/build-release.sh
  scripts/publish-next.sh
  scripts/publish.sh
Labels: chore

#594 refactor(cryptography): use `@noble/hashes` for hashing
  packages/cryptography/package.json
  packages/cryptography/source/hash.test.ts
  packages/cryptography/source/hash.ts
  packages/profiles/source/cache.service.ts
  pnpm-lock.yaml
Labels: refactor

#596 chore(lsk): disable multiSignature for Lisk networks
  packages/lsk/source/__snapshots__/transaction.service.test.ts.snap
  packages/lsk/source/fee.service.test.ts
  packages/lsk/source/networks/shared.ts
  packages/lsk/source/transaction.service.test.ts
  packages/lsk/source/transaction.service.ts
  packages/profiles/test/musig/lsk.musig.registration.test.ts
Labels: chore

#601 refactor(cryptography): use `secp256k1` for non-schnorr functions
  packages/ark/package.json
  packages/cryptography/package.json
  packages/cryptography/source/secp256k1.ts
  pnpm-lock.yaml
Labels: refactor

#603 refactor: bundle `bcrypto` only with `ark`
  packages/ark/package.json
  packages/ark/source/crypto/hash.ts
  packages/atom/package.json
  packages/cryptography/package.json
  packages/cryptography/source/secp256k1.ts
  pnpm-lock.yaml
Labels: refactor

#605 refactor(cryptography): include bip32 implementation instead of dependency
  packages/ark/package.json
  packages/cryptography/package.json
  packages/cryptography/source/bip32.ts
  packages/cryptography/source/bip32/crypto.ts
  packages/cryptography/source/bip38.test.ts
  packages/cryptography/source/bip44.ts
  packages/cryptography/source/hash.ts
  pnpm-lock.yaml
Labels: refactor

#622 chore: rename `http-fetch` to `fetch`
  .github/workflows/ci.yml
  packages/ada/package.json
  packages/ada/test/mocking.ts
  packages/ark/package.json
  packages/ark/test/mocking.ts
  packages/atom/package.json
  packages/atom/test/mocking.ts
  packages/avax/package.json
  packages/avax/test/mocking.ts
  packages/btc/package.json
  packages/btc/test/mocking.ts
  packages/dot/package.json
  packages/dot/test/mocking.ts
  packages/egld/package.json
  packages/egld/test/mocking.ts
  packages/eos/package.json
  packages/eos/test/mocking.ts
  packages/eth/package.json
  packages/eth/test/mocking.ts
  packages/fetch/LICENSE
  packages/fetch/README.md
  packages/fetch/banner.png
  packages/fetch/package.json
  packages/fetch/source/index.ts
  packages/fetch/source/request.test.ts
  packages/fetch/source/request.ts
  packages/fetch/test/fixtures/feed.xml
  packages/fetch/tsconfig.json
  packages/lsk/package.json
  packages/lsk/test/mocking.ts
  packages/luna/package.json
  packages/luna/test/mocking.ts
  packages/markets/package.json
  packages/markets/source/drivers/coincap/index.test.js
  packages/markets/source/drivers/coingecko/index.test.js
  packages/markets/source/drivers/cryptocompare/index.test.js
  packages/markets/source/index.test.ts
  packages/nano/package.json
  packages/nano/test/mocking.ts
  packages/neo/package.json
  packages/neo/test/mocking.ts
  packages/news/package.json
  packages/news/source/blockfolio.test.ts
  packages/profiles/package.json
  packages/profiles/source/env.test.ts
  packages/profiles/test/mocking.ts
  packages/sdk/source/coin-factory.test.ts
  packages/sdk/source/coin.test.ts
  packages/sol/package.json
  packages/sol/test/mocking.ts
  packages/trx/package.json
  packages/trx/test/mocking.ts
  packages/xlm/package.json
  packages/xlm/test/mocking.ts
  packages/xrp/package.json
  packages/xrp/test/mocking.ts
  packages/zil/package.json
  packages/zil/test/mocking.ts
  pnpm-lock.yaml
  scripts/build-release.sh
Labels: chore

#628 test(dot): add network mocks
  packages/dot/source/transaction.service.test.ts
  packages/dot/test/fixtures/client/chain-get-block-hash.json
  packages/dot/test/fixtures/client/chain-get-finalized-head.json
  packages/dot/test/fixtures/client/chain-get-header.json
  packages/dot/test/fixtures/client/rpc-methods.json
  packages/dot/test/fixtures/client/state-get-metadata.json
  packages/dot/test/fixtures/client/state-get-runtime-version.json
  packages/dot/test/fixtures/client/state-get-storage-1.json
  packages/dot/test/fixtures/client/state-get-storage-2.json
  packages/dot/test/fixtures/client/state-get-storage-3.json
  packages/dot/test/fixtures/client/state-query-storage-at.json
  packages/dot/test/fixtures/client/system-chain.json
  packages/dot/test/fixtures/client/system-properties.json
Labels: test

#629 test(avax): add network mocks
  packages/avax/source/client.service.test.ts
  packages/avax/test/fixtures/client/avm-get-balance.json
  packages/avax/test/fixtures/client/avm-get-tx.json
  packages/avax/test/fixtures/client/platform-sample-validators.json
Labels: test

#637 test(profiles): fix `LocalStorage` test by using a memory driver
  package.json
  packages/profiles/package.json
  packages/profiles/source/local.storage.test.ts
  packages/profiles/source/local.storage.ts
  pnpm-lock.yaml
Labels: test

#642 refactor(cryptography): use `micro-base` for `base58` and `bech32` operations
  packages/ark/source/crypto/transactions/types/ipfs.ts
  packages/atom/source/address.service.ts
  packages/cryptography/package.json
  packages/cryptography/source/base58-check.test.ts
  packages/cryptography/source/base58-check.ts
  packages/cryptography/source/base58.test.ts
  packages/cryptography/source/base58.ts
  packages/cryptography/source/bech32.ts
  packages/trx/source/address.service.ts
  pnpm-lock.yaml
Labels: refactor

#643 refactor(cryptography): remove `AES` implementation
  packages/cryptography/package.json
  packages/cryptography/source/aes.test.ts
  packages/cryptography/source/aes.ts
  pnpm-lock.yaml
Labels: refactor

#645 refactor(eth): replace `web3` calls with more lightweight alternatives
  packages/cryptography/source/hash.ts
  packages/eth/package.json
  packages/eth/source/address.service.ts
  packages/eth/source/client.service.test.ts
  packages/eth/source/client.service.ts
  packages/eth/source/confirmed-transaction.dto.ts
  packages/eth/source/transaction.service.ts
  packages/eth/source/units.ts
  packages/eth/source/wallet.dto.ts
  pnpm-lock.yaml
Labels: refactor

#648 refactor(eth): remove `bn.js` dependency in favour of native `BigInt`
  packages/eth/package.json
  packages/eth/source/units.test.ts
  packages/eth/source/units.ts
  pnpm-lock.yaml
Labels: refactor

#661 refactor(profiles): disable portfolio latest transactions by default
  packages/profiles/source/appearance.service.test.ts
  packages/profiles/source/appearance.service.ts
  packages/profiles/source/env.test.ts
Labels: refactor

#660 refactor(cryptography): replace BIP38 implementation
  packages/cryptography/package.json
  packages/cryptography/source/bip38.test.ts
  packages/cryptography/source/bip38.ts
  packages/cryptography/source/bip39.test.ts
  packages/cryptography/source/hash.ts
  pnpm-lock.yaml
Labels: refactor

#663 refactor(cryptography): integrate `ecurve`
  packages/cryptography/package.json
  packages/cryptography/source/bip38.ts
  packages/cryptography/source/ecurve/curve.ts
  packages/cryptography/source/ecurve/names.ts
  packages/cryptography/source/ecurve/point.ts
  pnpm-lock.yaml
Labels: refactor

#666 refactor(profiles): remove bip38 dependency
  packages/cryptography/source/index.ts
  packages/profiles/package.json
  packages/profiles/source/wallet.factory.test.ts
  packages/profiles/source/wallet.factory.ts
  packages/profiles/source/wallet.identifier.factory.test.ts
  pnpm-lock.yaml
Labels: refactor
