Repository ArkEcosystem/payvo-sdk, pull requests merged in 2022-01, with the labels that each got.

#672 refactor(cryptography): replace `bip39` with `micro-bip39`
  packages/ada/source/shelley.ts
  packages/avax/source/helpers.ts
  packages/cryptography/package.json
  packages/cryptography/source/bip32.ts
  packages/cryptography/source/bip39.test.ts
  packages/cryptography/source/bip39.ts
  packages/sol/source/keys.ts
  packages/xlm/source/helpers.ts
  pnpm-lock.yaml
Labels: refactor

#669 refactor(cryptography): use `@peculiar/webcrypto` for AES encryption
  packages/cryptography/package.json
  packages/cryptography/source/pbkdf2.test.ts
  packages/cryptography/source/pbkdf2.ts
  packages/profiles/package.json
  packages/profiles/source/authenticator.test.ts
  packages/profiles/source/environment.test.ts
  packages/profiles/source/exchange-rate.service.test.ts
  packages/profiles/source/multi-signature.test.ts
  packages/profiles/source/portfolio.test.ts
  packages/profiles/source/profile.dumper.test.ts
  packages/profiles/source/profile.encrypter.contract.ts
  packages/profiles/source/profile.encrypter.test.ts
  packages/profiles/source/profile.encrypter.ts
  packages/profiles/source/profile.exporter.contract.ts
  packages/profiles/source/profile.exporter.ts
  packages/profiles/source/profile.importer.test.ts
  packages/profiles/source/profile.importer.ts
  packages/profiles/source/profile.repository.contract.ts
  packages/profiles/source/profile.repository.test.ts
  packages/profiles/source/profile.repository.ts
  packages/profiles/source/profile.validator.test.ts
  packages/profiles/source/serialiser.test.ts
  packages/profiles/source/signatory.factory.test.ts
  packages/profiles/source/signatory.factory.ts
  packages/profiles/source/transaction-index.test.ts
  packages/profiles/source/vote-registry.test.ts
  packages/profiles/source/wallet.factory.test.ts
  packages/profiles/source/wallet.factory.ts
  packages/profiles/source/wallet.gate.test.ts
  packages/profiles/source/wallet.identifier.factory.test.ts
  packages/profiles/source/wallet.mutator.test.ts
  packages/profiles/source/wallet.mutator.ts
  packages/profiles/source/wallet.service.test.ts
  packages/profiles/source/wallet.synchroniser.test.ts
  packages/profiles/source/wallet.test.ts
  packages/profiles/source/wif.contract.ts
  packages/profiles/source/wif.test.ts
  packages/profiles/source/wif.ts
  packages/profiles/test/profiles.ts
  pnpm-lock.yaml
Labels: refactor

#665 chore: use `babel` for production bundling
  package.json
  pnpm-lock.yaml
  webpack.config.cjs
Labels: chore

#677 fix(sol): use `SOL` as export name
  packages/sol/source/index.ts
Labels: bugfix

#680 chore(helpers): integrate fast sort
  packages/helpers/package.json
  packages/helpers/source/fast-sort.ts
  packages/helpers/source/immutable/sort-by-desc.ts
  packages/helpers/source/immutable/sort-by.ts
  packages/helpers/source/order-by.ts
  packages/helpers/source/sort-by-desc.ts
  packages/helpers/source/sort-by.ts
  pnpm-lock.yaml
Labels: chore

#678 chore: update eslint `import/extensions` rule
  .eslintignore
  .eslintrc.bash.json
  .eslintrc.json
  packages/fetch/source/request.test.ts
  packages/intl/source/currencies.test.ts
  packages/intl/source/currency.test.ts
  packages/intl/source/datetime.test.ts
  packages/intl/source/money.test.ts
  packages/intl/source/numeral.test.ts
  packages/news/source/blockfolio.test.ts
  packages/news/source/feed.test.ts
  packages/sdk/source/big-number.service.test.ts
  packages/sdk/source/coin-factory.test.ts
  packages/sdk/source/coin.test.ts
  packages/sdk/source/config.test.ts
  packages/sdk/source/container.test.ts
  packages/sdk/source/enums.test.ts
  packages/sdk/source/exceptions.test.ts
  packages/sdk/source/http-exceptions.test.ts
  packages/sdk/source/http-response.test.ts
  packages/sdk/source/http-urls.test.ts
  packages/sdk/source/index.ts
  packages/sdk/source/manifest.test.ts
  packages/sdk/source/network-repository.test.ts
  packages/sdk/source/network.test.ts
  packages/sdk/source/paginator.test.ts
  packages/sdk/source/signatory.test.ts
  packages/sdk/source/transactions.collection.test.ts
  packages/sdk/source/wallets.collection.test.ts
Labels: chore

#681 chore(profiles): drop screenshot protection setting
  packages/profiles/source/environment.test.ts
  packages/profiles/source/migrator.test.ts
  packages/profiles/source/profile.enum.contract.ts
  packages/profiles/source/profile.importer.test.ts
  packages/profiles/source/profile.initialiser.ts
  packages/profiles/source/profile.test.ts
  packages/profiles/source/profile.validator.test.ts
  packages/profiles/source/profile.validator.ts
Labels: chore

#682 refactor(ark): implement `ByteBuffer` for browser support
  packages/ark/package.json
  packages/ark/source/crypto/interfaces/transactions.ts
  packages/ark/source/crypto/transactions/deserializer.ts
  packages/ark/source/crypto/transactions/serializer.ts
  packages/ark/source/crypto/transactions/types/delegate-registration.ts
  packages/ark/source/crypto/transactions/types/delegate-resignation.ts
  packages/ark/source/crypto/transactions/types/ipfs.ts
  packages/ark/source/crypto/transactions/types/multi-payment.ts
  packages/ark/source/crypto/transactions/types/multi-signature-registration.ts
  packages/ark/source/crypto/transactions/types/second-signature-registration.ts
  packages/ark/source/crypto/transactions/types/transaction.ts
  packages/ark/source/crypto/transactions/types/transfer.ts
  packages/ark/source/crypto/transactions/types/vote.ts
  packages/ark/source/multi-signature.service.test.ts
  packages/ark/source/multi-signature.service.ts
  packages/btc/source/ledger.service.ts
  packages/helpers/source/bignumber.test.ts
  packages/helpers/source/bignumber.ts
  packages/helpers/source/byte-buffer.test.ts
  packages/helpers/source/byte-buffer.ts
  packages/helpers/source/index.ts
  pnpm-lock.yaml
Labels: bugfix

#683 refactor(cryptography): normalise value into `Uint8Array` before hashing
  packages/cryptography/source/hash.ts
Labels: refactor

#684 refactor(cryptography): turn signatures, hashes and keys into `Uint8Array`
  packages/cryptography/source/hash.ts
  packages/cryptography/source/internal/buffer-to-uint8array.ts
  packages/cryptography/source/secp256k1.ts
Labels: refactor

#685 refactor(cryptography): normalise all buffers into `Uint8Array`
  packages/cryptography/source/base58-check.ts
  packages/cryptography/source/base58.ts
  packages/cryptography/source/buffoon.ts
  packages/cryptography/source/hash.ts
  packages/cryptography/source/hdkey.ts
  packages/cryptography/source/internal/buffer-to-uint8array.ts
Labels: refactor

#687 chore: update production dependencies
  packages/ada/package.json
  packages/avax/package.json
  packages/btc/package.json
  packages/cryptography/package.json
  packages/cryptography/source/base58-check.ts
  packages/cryptography/source/bip38.ts
  packages/cryptography/source/hash.ts
  packages/dot/package.json
  packages/egld/package.json
  packages/egld/source/message.service.ts
  packages/eth/package.json
  packages/fetch/package.json
  packages/helpers/package.json
  packages/ledger/package.json
  packages/luna/package.json
  packages/nano/package.json
  packages/nano/source/message.service.ts
  packages/profiles/package.json
  packages/sdk/package.json
  packages/sol/package.json
  packages/test/package.json
  packages/trx/package.json
  packages/xlm/package.json
  packages/xrp/package.json
  pnpm-lock.yaml
Labels: chore

#690 fix(profiles): check correct attribute for custom avatar
  packages/profiles/source/profile.ts
Labels: bugfix

#688 test: cover encrypted profile import from browser and node environments
  packages/profiles/source/profile.repository.test.ts
  packages/profiles/test/fixtures/profiles/empty-profile.wwe
  packages/profiles/test/fixtures/profiles/password-protected-profile.wwe
Labels: test

#692 fix(ark): validate address based on network configuration
  packages/ark/source/address.service.ts
  packages/ark/source/crypto/identities/address.ts
Labels: bugfix

#694 fix: multisignature signer initialization
  packages/ark/source/transaction.service.ts
Labels: bugfix

#695 feat(eth): implement wallet & ERC20 balances
  packages/eth/source/client.service.test.ts
  packages/eth/source/client.service.ts
  packages/eth/source/confirmed-transaction.dto.ts
  packages/eth/source/networks/eth.kovan.ts
  packages/eth/source/networks/eth.mainnet.ts
  packages/eth/source/networks/eth.rinkeby.ts
  packages/eth/source/networks/eth.ropsten.ts
  packages/eth/source/transaction.dto.test.ts
  packages/eth/source/wallet.dto.test.ts
  packages/eth/source/wallet.dto.ts
  packages/eth/test/fixtures/client/transaction.json
  packages/eth/test/fixtures/client/transactions.json
  packages/eth/test/fixtures/client/wallet.json
Labels: feature

#698 refactor: implement LedgerTransportFactory#supportedTransport()
  packages/ark/test/mocking.ts
  packages/ledger/package.json
  packages/ledger/source/index.ts
  pnpm-lock.yaml
Labels: refactor

#699 chore(ark): adjust BPL api url
  packages/ark/source/networks/bpl.mainnet.ts
Labels: chore

#700 chore: build `esm` files for release
  package.json
Labels: bugfix

#701 chore(ark): disable vendorfields on BIND networks
  packages/ark/source/networks/bind.mainnet.ts
  packages/ark/source/networks/bind.testnet.ts
Labels: chore

#702 fix(ark): reliable way to calculate multisign fees
  packages/ark/source/fee.service.test.ts
  packages/ark/source/fee.service.ts
Labels: bugfix

#703 fix: profile not persisting randomly
  packages/profiles/source/environment.test.ts
  packages/profiles/source/environment.ts
Labels: bugfix
