Repository ArkEcosystem/payvo-sdk, pull requests merged in 2022-04, with the labels that each got.

#720 chore(ark): adjust SXP network configs
  packages/ark/source/networks/sxp.mainnet.ts
  packages/ark/source/networks/sxp.testnet.ts
  packages/sdk/source/network-repository.test.ts
Labels: chore

#721 refactor(sdk): check if transaction type is vote combination before other types
  packages/sdk/source/confirmed-transaction.dto.ts
  packages/sdk/source/signed-transaction.dto.ts
Labels: refactor

#719 fix(profiles): ensure MuSig transaction has correct data types before broadcasting
  packages/profiles/source/wallet-transaction.service.ts
  packages/sdk/source/signed-transaction.dto.contract.ts
  packages/sdk/source/signed-transaction.dto.test.ts
  packages/sdk/source/signed-transaction.dto.ts
  packages/xlm/source/signed-transaction.dto.ts
Labels: bugfix

#722 refactor(profiles): include network id in wallet lookup of transaction aggregate
  packages/profiles/source/transaction.aggregate.test.ts
  packages/profiles/source/transaction.aggregate.ts
  packages/sdk/source/client.contract.ts
Labels: refactor

#723 chore(ark): remove SXP networks
  packages/ark/source/link.service.test.ts
  packages/ark/source/manifest.ts
  packages/ark/source/networks/sxp.mainnet.ts
  packages/ark/source/networks/sxp.testnet.ts
  packages/profiles/source/environment.test.ts
  packages/sdk/source/network-repository.test.ts
Labels: chore

#725 feat: add FallbackToDefaultNodes user profile setting
  packages/profiles/source/environment.test.ts
  packages/profiles/source/migrator.test.ts
  packages/profiles/source/profile.enum.contract.ts
  packages/profiles/source/profile.importer.test.ts
  packages/profiles/source/profile.initialiser.ts
  packages/profiles/source/profile.test.ts
  packages/profiles/source/profile.validator.test.ts
  packages/profiles/source/profile.validator.ts
Labels: refactor

#728 fix(ark): normalize transaction data on broadcast
  packages/ark/source/signed-transaction.dto.ts
  packages/sdk/source/signed-transaction.dto.ts
Labels: bugfix

#729 refactor: make new FallbackToDefaultNodes setting optional
  packages/profiles/source/profile.validator.ts
Labels: refactor

#731 refactor(bind): disable multisignature feature
  packages/ark/source/networks/bind.mainnet.ts
  packages/ark/source/networks/bind.testnet.ts
Labels: refactor

#732 feat(profiles): add support for host names
  packages/profiles/source/coin.service.ts
  packages/profiles/source/host.repository.contract.ts
  packages/profiles/source/host.repository.test.ts
  packages/profiles/source/host.repository.ts
Labels: feature

#734 fix: removing an element by index removes all items if using zero
  packages/profiles/source/host.repository.test.ts
  packages/profiles/source/host.repository.ts
Labels: bugfix

#733 chore(profiles): replace default accent color
  packages/profiles/source/appearance.service.test.ts
  packages/profiles/source/appearance.service.ts
  packages/profiles/source/environment.test.ts
  packages/profiles/source/migrator.test.ts
  packages/profiles/source/profile.importer.test.ts
  packages/profiles/source/profile.initialiser.test.ts
  packages/profiles/source/profile.validator.test.ts
Labels: chore

#736 refactor(ark): mark hosts as failed if a server error is encounter
  packages/ark/source/client.service.ts
  packages/ark/source/coin.provider.ts
  packages/ark/source/fee.service.ts
  packages/ark/source/multi-signature.service.ts
  packages/ark/source/request.ts
  packages/ark/source/transaction.service.ts
  packages/sdk/source/network.models.ts
Labels: refactor

#737 feat(profiles): add enabled flag to the host object
  packages/profiles/source/host.repository.test.ts
  packages/sdk/source/network.models.ts
Labels: feature

#742 refactor: store height in host repository
  packages/profiles/source/host.repository.test.ts
  packages/sdk/source/network.models.ts
Labels: refactor

#743 feat: implement `ProberService`
  packages/ark/source/index.ts
  packages/ark/source/prober.service.ts
  packages/sdk/source/coin.ts
  packages/sdk/source/prober.contract.ts
  packages/sdk/source/prober.service.ts
  packages/sdk/source/service-provider.contract.ts
  packages/sdk/source/service-provider.ts
  packages/sdk/source/services.ts
Labels: feature
