Repository ArkEcosystem/payvo-sdk, pull requests merged in 2022-02, with the labels that each got.

#704 refactor(ark): add progress handler to track the loaded wallets
  packages/ark/source/ledger.service.ts
Labels: refactor

#705 fix(sdk): update scan method contract
  packages/sdk/source/ledger.contract.ts
Labels: refactor

#706 fix: adjust the URI generator
  packages/helpers/source/uri.test.ts
  packages/helpers/source/uri.ts
Labels: bugfix

#707 refactor: automatically cast `BigNumber` instances in assertions
  packages/ark/source/confirmed-transaction.dto.test.ts
  packages/ark/source/wallet.dto.test.ts
  packages/atom/source/client.service.test.ts
  packages/btc/source/client.service.test.ts
  packages/eos/source/wallet.dto.test.ts
  packages/lsk/source/transaction.dto.test.ts
  packages/neo/source/wallet.dto.test.ts
  packages/test/package.json
  packages/test/source/assert.test.ts
  packages/test/source/assert.ts
  packages/trx/source/wallet.dto.test.ts
  packages/xlm/source/client.service.test.ts
  packages/xlm/source/wallet.dto.test.ts
  packages/xrp/source/client.service.test.ts
  packages/xrp/source/confirmed-transaction.dto.test.ts
  packages/xrp/source/wallet.dto.test.ts
  packages/zil/source/client.service.test.ts
  pnpm-lock.yaml
Labels: refactor

#708 refactor: accept payload as string in `LedgerService#signMessage`
  packages/ark/source/ledger.service.test.ts
  packages/ark/source/ledger.service.ts
  packages/atom/source/ledger.service.test.ts
  packages/btc/source/ledger.service.test.ts
  packages/btc/source/ledger.service.ts
  packages/dot/source/ledger.service.test.ts
  packages/eos/source/ledger.service.test.ts
  packages/eth/source/ledger.service.test.ts
  packages/eth/source/ledger.service.ts
  packages/lsk/source/ledger.service.test.ts
  packages/lsk/source/ledger.service.ts
  packages/neo/source/ledger.service.test.ts
  packages/sdk/source/ledger.contract.ts
  packages/sdk/source/ledger.service.ts
  packages/trx/source/ledger.service.test.ts
  packages/xlm/source/ledger.service.test.ts
  packages/xrp/source/ledger.service.test.ts
Labels: refactor

#709 feat(profiles): implement `HostRepository`
  packages/profiles/package.json
  packages/profiles/source/host.repository.contract.ts
  packages/profiles/source/host.repository.test.ts
  packages/profiles/source/host.repository.ts
  packages/profiles/source/profile.contract.ts
  packages/profiles/source/profile.ts
  packages/sdk/source/network.models.ts
Labels: feature

#710 feat(profiles): implement `NetworkRepository`
  packages/profiles/package.json
  packages/profiles/source/network.repository.contract.ts
  packages/profiles/source/network.repository.test.ts
  packages/profiles/source/network.repository.ts
  packages/profiles/source/profile.contract.ts
  packages/profiles/source/profile.ts
  packages/profiles/test/mocking.ts
Labels: feature

#711 feat(profiles): attach custom networks to coin instance
  packages/ark/source/coin.provider.ts
  packages/profiles/package.json
  packages/profiles/source/coin.service.test.ts
  packages/profiles/source/coin.service.ts
  packages/profiles/source/network.repository.contract.ts
  packages/profiles/source/network.repository.test.ts
  packages/profiles/source/network.repository.ts
  packages/profiles/source/profile.contract.ts
  packages/profiles/source/profile.serialiser.ts
  packages/profiles/source/profile.ts
Labels: feature

#712 feat(profiles): attach custom hosts to network manifest
  packages/profiles/source/coin.service.ts
  packages/profiles/source/host.repository.contract.ts
  packages/profiles/source/host.repository.test.ts
  packages/profiles/source/host.repository.ts
Labels: feature

#713 fix(profiles): restore custom hosts and networks
  packages/profiles/source/profile.importer.test.ts
  packages/profiles/source/profile.importer.ts
  packages/profiles/source/profile.repository.test.ts
  packages/profiles/source/profile.validator.test.ts
  packages/profiles/source/profile.validator.ts
Labels: bugfix

#715 fix(profiles): multisign transaction payload
  packages/profiles/source/wallet-transaction.service.ts
Labels: bugfix
